//! Literal syntax projection of the authoritative75-case private contract.
//! The six valid-syntax Input refusals normalize here; schema checks are later.
use super::super::Json5SyntaxKind;

pub(super) struct Case {
    pub id: &'static str,
    pub input: &'static str,
    pub normalized: Option<&'static str>,
    pub error: Option<Json5SyntaxKind>,
}

pub(super) const CASES: &[Case] = &[
    Case {
        id: "strict-integer",
        input: "{\"n\":7}",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "comments-trailing-comma",
        input: "/*before*/{n:7,}// eof",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "unicode-text-single-quotes",
        input: "{n:'Ada 雪'}",
        normalized: Some("{\"n\":\"Ada 雪\"}"),
        error: None,
    },
    Case {
        id: "hexadecimal",
        input: "{n:0x10}",
        normalized: Some("{\"n\":16}"),
        error: None,
    },
    Case {
        id: "hexadecimal-negative",
        input: "{n:-0X10}",
        normalized: Some("{\"n\":-16}"),
        error: None,
    },
    Case {
        id: "leading-plus",
        input: "{n:+7}",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "leading-point",
        input: "{n:.5}",
        normalized: Some("{\"n\":0.5}"),
        error: None,
    },
    Case {
        id: "trailing-point",
        input: "{n:5.}",
        normalized: Some("{\"n\":5.0}"),
        error: None,
    },
    Case {
        id: "plus-leading-point",
        input: "{n:+.5}",
        normalized: Some("{\"n\":0.5}"),
        error: None,
    },
    Case {
        id: "exponent-retained",
        input: "{n:1e0}",
        normalized: Some("{\"n\":1e0}"),
        error: None,
    },
    Case {
        id: "integer-minus-zero-native-tag",
        input: "{n:-0}",
        normalized: Some("{\"n\":0}"),
        error: None,
    },
    Case {
        id: "hex-minus-zero-native-tag",
        input: "{n:-0x0}",
        normalized: Some("{\"n\":0}"),
        error: None,
    },
    Case {
        id: "float-minus-zero",
        input: "{n:-0.0}",
        normalized: Some("{\"n\":-0.0}"),
        error: None,
    },
    Case {
        id: "bool",
        input: "{n:true}",
        normalized: Some("{\"n\":true}"),
        error: None,
    },
    Case {
        id: "nullable-explicit-null",
        input: "{n:null}",
        normalized: Some("{\"n\":null}"),
        error: None,
    },
    Case {
        id: "i64-min-hex",
        input: "{n:-0x8000000000000000}",
        normalized: Some("{\"n\":-9223372036854775808}"),
        error: None,
    },
    Case {
        id: "i64-max",
        input: "{n:9223372036854775807}",
        normalized: Some("{\"n\":9223372036854775807}"),
        error: None,
    },
    Case {
        id: "integer-two53-plus1",
        input: "{n:9007199254740993}",
        normalized: Some("{\"n\":9007199254740993}"),
        error: None,
    },
    Case {
        id: "decimal-two53-plus1-rounds-once",
        input: "{n:9007199254740993.0}",
        normalized: Some("{\"n\":9007199254740993.0}"),
        error: None,
    },
    Case {
        id: "escaped-ascii-identifier",
        input: "{\\u006e:7}",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "duplicate-last-wins",
        input: "{n:1,n:7}",
        normalized: Some("{\"n\":1,\"n\":7}"),
        error: None,
    },
    Case {
        id: "escaped-duplicate-name",
        input: "{n:1,'\\u006e':7}",
        normalized: Some("{\"n\":1,\"n\":7}"),
        error: None,
    },
    Case {
        id: "earlier-type-replaced",
        input: "{n:'bad',n:7}",
        normalized: Some("{\"n\":\"bad\",\"n\":7}"),
        error: None,
    },
    Case {
        id: "quoted-unicode-name",
        input: "{'雪':7}",
        normalized: Some("{\"雪\":7}"),
        error: None,
    },
    Case {
        id: "bom-and-json5-whitespace",
        input: "﻿ {n:7}  ",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "line-comment-u2028",
        input: "// before {n:7}",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "line-comment-u2029",
        input: "// before {n:7}",
        normalized: Some("{\"n\":7}"),
        error: None,
    },
    Case {
        id: "lf-string-continuation",
        input: "{n:'a\\\nb'}",
        normalized: Some("{\"n\":\"ab\"}"),
        error: None,
    },
    Case {
        id: "crlf-string-continuation",
        input: "{n:'a\\\r\nb'}",
        normalized: Some("{\"n\":\"ab\"}"),
        error: None,
    },
    Case {
        id: "separator-string-continuation",
        input: "{n:'a\\ b'}",
        normalized: Some("{\"n\":\"ab\"}"),
        error: None,
    },
    Case {
        id: "hex-string-escape",
        input: "{n:'\\x41'}",
        normalized: Some("{\"n\":\"A\"}"),
        error: None,
    },
    Case {
        id: "surrogate-pair-string",
        input: "{n:'\\uD83D\\uDE00'}",
        normalized: Some("{\"n\":\"😀\"}"),
        error: None,
    },
    Case {
        id: "non-escape-character",
        input: "{n:'\\z'}",
        normalized: Some("{\"n\":\"z\"}"),
        error: None,
    },
    Case {
        id: "nul-escape",
        input: "{n:'\\0'}",
        normalized: Some("{\"n\":\"\\u0000\"}"),
        error: None,
    },
    Case {
        id: "vertical-tab-escape",
        input: "{n:'\\v'}",
        normalized: Some("{\"n\":\"\\u000b\"}"),
        error: None,
    },
    Case {
        id: "raw-tab-string",
        input: "{n:'a\tb'}",
        normalized: Some("{\"n\":\"a\\tb\"}"),
        error: None,
    },
    Case {
        id: "raw-u2028-string",
        input: "{n:'a b'}",
        normalized: Some("{\"n\":\"a b\"}"),
        error: None,
    },
    Case {
        id: "markers-in-string-not-comments",
        input: "{n:'/*not comment*/ [] {} //'}",
        normalized: Some("{\"n\":\"/*not comment*/ [] {} //\"}"),
        error: None,
    },
    Case {
        id: "unquoted-unicode-boundary",
        input: "{雪:7}",
        normalized: None,
        error: Some(Json5SyntaxKind::UnsupportedIdentifier),
    },
    Case {
        id: "escaped-unicode-identifier-boundary",
        input: "{\\u96ea:7}",
        normalized: None,
        error: Some(Json5SyntaxKind::UnsupportedIdentifier),
    },
    Case {
        id: "consecutive-comma",
        input: "{n:7,,}",
        normalized: None,
        error: Some(Json5SyntaxKind::UnexpectedToken),
    },
    Case {
        id: "missing-colon",
        input: "{n 7}",
        normalized: None,
        error: Some(Json5SyntaxKind::UnexpectedToken),
    },
    Case {
        id: "second-root-json-lines",
        input: "{n:7}\n{n:8}",
        normalized: None,
        error: Some(Json5SyntaxKind::TrailingRootValue),
    },
    Case {
        id: "unterminated-block-comment",
        input: "{n:7}/*",
        normalized: None,
        error: Some(Json5SyntaxKind::UnterminatedComment),
    },
    Case {
        id: "unescaped-lf-string",
        input: "{n:'a\nb'}",
        normalized: None,
        error: Some(Json5SyntaxKind::LineTerminatorInString),
    },
    Case {
        id: "unpaired-surrogate-string",
        input: "{n:'\\uD800'}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidEscape),
    },
    Case {
        id: "reversed-surrogate-string",
        input: "{n:'\\uDC00\\uD800'}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidEscape),
    },
    Case {
        id: "legacy-octal-string-escape",
        input: "{n:'\\1'}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidEscape),
    },
    Case {
        id: "nul-followed-digit",
        input: "{n:'\\01'}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidEscape),
    },
    Case {
        id: "invalid-hex-string-escape",
        input: "{n:'\\x0G'}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidEscape),
    },
    Case {
        id: "number-leading-zero",
        input: "{n:01}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidNumber),
    },
    Case {
        id: "number-separator",
        input: "{n:1_0}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidNumber),
    },
    Case {
        id: "empty-hexadecimal",
        input: "{n:0x}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidNumber),
    },
    Case {
        id: "empty-exponent",
        input: "{n:1e+}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidNumber),
    },
    Case {
        id: "unsigned64-plus1",
        input: "{n:18446744073709551616}",
        normalized: None,
        error: Some(Json5SyntaxKind::IntegerOutOfRange),
    },
    Case {
        id: "signed64-minus1",
        input: "{n:-9223372036854775809}",
        normalized: None,
        error: Some(Json5SyntaxKind::IntegerOutOfRange),
    },
    Case {
        id: "float-overflow",
        input: "{n:1e400}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-Infinity",
        input: "{n:Infinity}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-minusInfinity",
        input: "{n:-Infinity}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-plusInfinity",
        input: "{n:+Infinity}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-NaN",
        input: "{n:NaN}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-minusNaN",
        input: "{n:-NaN}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-plusNaN",
        input: "{n:+NaN}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "nonfinite-overwritten",
        input: "{n:NaN,n:null}",
        normalized: None,
        error: Some(Json5SyntaxKind::NonFiniteNumber),
    },
    Case {
        id: "earlier-invalid-escape-overwritten",
        input: "{n:'\\1',n:'valid'}",
        normalized: None,
        error: Some(Json5SyntaxKind::InvalidEscape),
    },
    Case {
        id: "nul-unquoted-value",
        input: "{n:\u{0}}",
        normalized: None,
        error: Some(Json5SyntaxKind::UnexpectedToken),
    },
    Case {
        id: "NEL-not-json5-whitespace",
        input: "{n:7}",
        normalized: None,
        error: Some(Json5SyntaxKind::UnexpectedToken),
    },
    Case {
        id: "root-array-not-flat-rows",
        input: "[{n:7}]",
        normalized: Some("[{\"n\":7}]"),
        error: None,
    },
    Case {
        id: "nonnullable-null",
        input: "{n:null}",
        normalized: Some("{\"n\":null}"),
        error: None,
    },
    Case {
        id: "decimal-not-integer-tag",
        input: "{n:1.0}",
        normalized: Some("{\"n\":1.0}"),
        error: None,
    },
    Case {
        id: "u64-outside-signed-int",
        input: "{n:9223372036854775808}",
        normalized: Some("{\"n\":9223372036854775808}"),
        error: None,
    },
    Case {
        id: "integer-not-exact-float",
        input: "{n:9007199254740993}",
        normalized: Some("{\"n\":9007199254740993}"),
        error: None,
    },
    Case {
        id: "undeclared-property",
        input: "{n:7,x:8}",
        normalized: Some("{\"n\":7,\"x\":8}"),
        error: None,
    },
    Case {
        id: "absent-remains-null",
        input: "{}",
        normalized: Some("{}"),
        error: None,
    },
    Case {
        id: "duplicate-first-key-slot-schema-order",
        input: "{m:3,n:1,n:7}",
        normalized: Some("{\"m\":3,\"n\":1,\"n\":7}"),
        error: None,
    },
];
