pub(super) const CASES: &[(&str, &str, &str, &str, bool, &str)] = &[
    ("α", "(?u)(\\p{Greek})", "", "[$1]", true, "[α]"),
    ("Ϣ", "(?u)(\\p{Greek})", "", "[$1]", false, "Ϣ"),
    ("͸", "(?u)(\\p{IsGreek})", "", "[$1]", false, "͸"),
    ("𝈀", "(?u)(\\p{sc=Grek})", "", "[$1]", true, "[𝈀]"),
    ("͂", "(?u)(\\p{sc=Greek})", "", "[$1]", false, "͂"),
    ("͂", "(?u)(\\p{scx=Greek})", "", "[$1]", true, "[͂]"),
    (
        "·",
        "(?U)(\\p{Script_Extensions:Grek})",
        "",
        "[$1]",
        true,
        "[·]",
    ),
    ("ー", "(?R)(\\p{sc=Common})", "", "[$1]", true, "[ー]"),
    ("ー", "(?R)(\\p{scx=Common})", "", "[$1]", false, "ー"),
    ("ー", "(?u)(\\p{scx=Hira})", "", "[$1]", true, "[ー]"),
    ("ー", "(?u)(\\p{scx=Kana})", "", "[$1]", true, "[ー]"),
    ("͂", "(?u)(\\p{sc=Inherited})", "", "[$1]", true, "[͂]"),
    ("͂", "(?u)(\\p{scx=Inherited})", "", "[$1]", false, "͂"),
    ("µ", "(?u)(\\p{Greek})", "", "[$1]", false, "µ"),
    ("µ", "(?iu)(\\p{Greek})", "", "[$1]", true, "[µ]"),
    ("µ", "(?iu)(\\P{Greek})", "", "[$1]", false, "µ"),
    ("µ", "(?iu)(\\p{sc!=Greek})", "", "[$1]", false, "µ"),
    ("α", "(?u)(\\P{sc!=Greek})", "", "[$1]", true, "[α]"),
    ("ͅ", "(?iu)(\\p{Greek})", "", "[$1]", true, "[ͅ]"),
    ("𐐨", "(?iu)(\\p{Deseret})", "", "[$1]", true, "[𐐨]"),
    ("𖵀", "(?u)(\\p{Kirat_Rai})", "", "[$1]", true, "[𖵀]"),
    ("𑎀", "(?u)(\\p{Tulu_Tigalari})", "", "[$1]", true, "[𑎀]"),
    ("𞗐", "(?u)(\\p{Ol_Onal})", "", "[$1]", true, "[𞗐]"),
    ("𑯰", "(?u)(\\p{Sunuwar})", "", "[$1]", true, "[𑯰]"),
    ("$", "(?u)(\\p{sc})", "", "[$1]", true, "[$]"),
    ("‍", "(?u)(\\p{Cf})", "", "[$1]", true, "[‍]"),
    ("A", "(?u)(\\p{Lc})", "", "[$1]", true, "[A]"),
    ("α", "(?u)(\\p{sc=Latin})", "", "[$1]", false, "α"),
    (
        "αA·",
        "(?u)([\\p{scx=Greek}--\\p{sc=Greek}])",
        "",
        "[$1]",
        true,
        "αA[·]",
    ),
    (
        "αAΩ",
        "(?u)([\\p{Greek}&&\\p{Ll}])",
        "",
        "[$1]",
        true,
        "[α]AΩ",
    ),
    (
        "αA",
        "(?u)([\\p{Greek}~~\\p{Latin}])",
        "",
        "[$1]",
        true,
        "[α][A]",
    ),
    ("α🙂A", "(?u)([^\\p{Greek}])", "", "[$1]", true, "α[🙂][A]"),
    (
        "xαβyΩZ",
        "(?u)(?<letters>\\p{Greek}+)",
        "",
        "[$1]",
        true,
        "x[αβ]y[Ω]Z",
    ),
    ("αβ", "(?U)(\\p{Greek}+)", "", "[$1]", true, "[α][β]"),
    ("αβ", "(?U)(\\p{Greek}+?)", "", "[$1]", true, "[αβ]"),
    (
        "α\r\nβ",
        "(?mR)(^\\p{Greek}+$)",
        "",
        "[$1]",
        true,
        "[α]\r\n[β]",
    ),
    (
        "αAβ",
        "(?u)(?-u:(A))|(\\p{Greek})",
        "",
        "[$1/$2]",
        true,
        "[/α][A/][/β]",
    ),
    ("·", "(?U)(?-U:(\\p{scx=Greek}))", "", "[$1]", true, "[·]"),
    ("α", "(?R)(?-R:(\\p{Greek}))", "", "[$1]", true, "[α]"),
    (
        "·",
        "(?xU)( \\p { Script_Extensions = Greek } )",
        "",
        "[$1]",
        true,
        "[·]",
    ),
    (
        "·",
        "(?u)(\\p{ sCrIpT_eXtEnSiOnS =Is_G_r_e_e_k })",
        "",
        "[$1]",
        true,
        "[·]",
    ),
    ("α", "(?u)(\\p{Script!=Latin})", "", "[$1]", true, "[α]"),
    (
        "α",
        "(?u)(\\P{Script_Extensions!=Greek})",
        "",
        "[$1]",
        true,
        "[α]",
    ),
    ("α", "(?u)(\\p{Is Greek})", "", "[$1]", true, "[α]"),
];

pub(super) fn assert_rows(rows: &[serde_json::Value]) {
    assert_eq!(rows.len(), CASES.len());
    for (index, (row, &(_, pattern, _, _, matched, replaced))) in rows.iter().zip(CASES).enumerate()
    {
        assert_eq!(row["Match"], matched, "script case {index}: {pattern}");
        assert_eq!(row["Replaced"], replaced, "script case {index}: {pattern}");
    }
    assert_eq!(
        rows[32]["Tokens"],
        serde_json::json!([{ "Value": "x" }, { "Value": "y" }, { "Value": "Z" }])
    );
}
