//! Delimited flat file schema and instance read/write, backed by the `csv`
//! crate for correct quoting/escaping.
//!
//! A CSV file's row-schema is a non-repeating [`SchemaNode::Group`] of
//! scalar fields; the file's row-repetition itself is a format convention,
//! not something declared in the schema (unlike XML, where `repeating` is a
//! per-element schema property).
//! Empty cells default to [`Value::Null`]. [`CsvReadOptions`] can preserve
//! present empty text cells as empty strings while missing columns remain null.

use std::io::Read as _;
use std::path::Path;

use ir::{Instance, ScalarType, SchemaKind, SchemaNode, Value};
use thiserror::Error;

mod fixed_width;
mod read;

pub use read::{
    CsvReadOptions, from_str, from_str_with_dialect, from_str_with_options, from_str_with_quote,
    read, read_with_dialect, read_with_options, read_with_quote,
};

pub use fixed_width::{
    from_str_fixed_width, read_fixed_width, to_string_fixed_width, write_fixed_width,
};

#[derive(Debug, Error)]
pub enum CsvFormatError {
    #[error("csv error: {0}")]
    Csv(#[from] csv::Error),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("row schema must be a non-repeating group of non-repeating scalar fields")]
    UnsupportedSchema,
    #[error("column `{field}` cannot preserve a heterogeneous scalar union")]
    UnsupportedScalarUnion { field: String },
    #[error("row {row}: column `{field}` expected {expected:?}, got `{value}`")]
    Parse {
        row: usize,
        field: String,
        expected: ScalarType,
        value: String,
    },
    #[error("row {row}: expected {expected} column(s), got {got}")]
    ColumnCount {
        row: usize,
        expected: usize,
        got: usize,
    },
    #[error("row {row}: expected a group, got {got}")]
    RowShape { row: usize, got: &'static str },
    #[error("row {row}: missing column `{field}`")]
    MissingField { row: usize, field: String },
    #[error("row {row}: unexpected column `{field}`")]
    UnexpectedField { row: usize, field: String },
    #[error("row {row}: duplicate column `{field}`")]
    DuplicateField { row: usize, field: String },
    #[error("row {row}: column `{field}` expected {expected:?}, got {got}")]
    ValueType {
        row: usize,
        field: String,
        expected: ScalarType,
        got: &'static str,
    },
    #[error("`{0}` is not a valid CSV delimiter (must be a single-byte character)")]
    BadDelimiter(char),
    #[error("`{0}` is not a valid CSV quote (must be a printable ASCII character)")]
    BadQuote(char),
    #[error("CSV delimiter and quote must be different characters")]
    DelimiterQuoteConflict,
    #[error("CSV quote character cannot be set while quoting is disabled")]
    ConflictingQuoteSettings,
    #[error(
        "row {row}: column `{field}` contains a separator or record boundary and cannot be written without quoting"
    )]
    UnquotedFieldBoundary { row: usize, field: String },
    #[error(
        "header `{field}` contains a separator or record boundary and cannot be written without quoting"
    )]
    UnquotedHeaderBoundary { field: String },
    #[error(
        "row {row}: a single empty field cannot be written as a distinguishable row without quoting"
    )]
    UnquotedSingleEmptyRow { row: usize },
    #[error("CSV file has no rows to infer columns from")]
    EmptySample,
    #[error("CSV sample exceeds the 1 MiB preview limit")]
    SampleTooLarge,
    #[error("CSV sample has more than 256 columns")]
    SampleTooWide,
    #[error("fixed-width layout declares {got} field width(s), but the schema has {expected}")]
    FixedWidthFieldCount { expected: usize, got: usize },
    #[error("fixed-width record {record}: expected {expected} character(s), got only {got}")]
    PartialFixedWidthRecord {
        record: usize,
        expected: usize,
        got: usize,
    },
    #[error("fixed-width record {record}: expected {expected} character(s), got {got}")]
    FixedWidthRecordOverflow {
        record: usize,
        expected: usize,
        got: usize,
    },
    #[error(
        "row {row}: column `{field}` exceeds its fixed width of {width} character(s), got {got}"
    )]
    FixedWidthFieldOverflow {
        row: usize,
        field: String,
        width: usize,
        got: usize,
    },
}

/// Upper bounds for schema-authoring previews. Runtime CSV reads are unaffected.
pub const MAX_SAMPLE_BYTES: usize = 1024 * 1024;
pub const MAX_SAMPLE_ROWS: usize = 10;
pub const MAX_SAMPLE_COLUMNS: usize = 256;

/// Raw column labels and data rows for a bounded CSV source preview.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CsvSample {
    pub columns: Vec<String>,
    pub rows: Vec<Vec<String>>,
}

/// Samples a CSV file without loading the whole document. A header row supplies
/// column labels; otherwise labels are generated by column position. Wider
/// sampled data rows add generated labels that the author can edit.
pub fn sample(
    path: &Path,
    delimiter: Option<char>,
    has_headers: bool,
) -> Result<CsvSample, CsvFormatError> {
    sample_with_quote(path, delimiter, None, has_headers)
}

/// Sample a CSV source using an explicit single-byte quote character.
pub fn sample_with_quote(
    path: &Path,
    delimiter: Option<char>,
    quote: Option<char>,
    has_headers: bool,
) -> Result<CsvSample, CsvFormatError> {
    sample_with_dialect(path, delimiter, quote, false, has_headers)
}

/// Sample a CSV source with optional quote recognition disabled.
pub fn sample_with_dialect(
    path: &Path,
    delimiter: Option<char>,
    quote: Option<char>,
    quote_disabled: bool,
    has_headers: bool,
) -> Result<CsvSample, CsvFormatError> {
    let (delimiter, quote) = dialect_bytes(delimiter, quote, quote_disabled)?;
    let file = std::fs::File::open(path)?;
    let file_exceeds_limit = file.metadata()?.len() > MAX_SAMPLE_BYTES as u64;
    let mut reader = csv::ReaderBuilder::new()
        .has_headers(false)
        .flexible(true)
        .delimiter(delimiter)
        .quote(quote.unwrap_or(b'"'))
        .quoting(quote.is_some())
        .from_reader(file.take((MAX_SAMPLE_BYTES + 1) as u64));
    let mut records = Vec::new();
    let record_limit = MAX_SAMPLE_ROWS + usize::from(has_headers);
    for _ in 0..record_limit {
        let mut record = csv::StringRecord::new();
        match reader.read_record(&mut record) {
            Ok(true) => {}
            Ok(false) if file_exceeds_limit && reader.get_ref().limit() == 0 => {
                return Err(CsvFormatError::SampleTooLarge);
            }
            Ok(false) => break,
            Err(_) if file_exceeds_limit && reader.get_ref().limit() == 0 => {
                return Err(CsvFormatError::SampleTooLarge);
            }
            Err(error) => return Err(error.into()),
        }
        if reader.position().byte() > MAX_SAMPLE_BYTES as u64 {
            return Err(CsvFormatError::SampleTooLarge);
        }
        if record.len() > MAX_SAMPLE_COLUMNS {
            return Err(CsvFormatError::SampleTooWide);
        }
        records.push(record.iter().map(str::to_owned).collect::<Vec<_>>());
    }
    let Some(first) = records.first() else {
        return Err(CsvFormatError::EmptySample);
    };
    let width = records.iter().map(Vec::len).max().unwrap_or(0);
    let mut columns = if has_headers {
        first.clone()
    } else {
        Vec::new()
    };
    for index in columns.len()..width {
        columns.push(format!("Column {}", index + 1));
    }
    let rows = if has_headers {
        records.into_iter().skip(1).collect()
    } else {
        records
    };
    Ok(CsvSample { columns, rows })
}

fn delimiter_byte(delimiter: Option<char>) -> Result<u8, CsvFormatError> {
    match delimiter {
        None => Ok(b','),
        Some(c) if c.is_ascii() => Ok(c as u8),
        Some(c) => Err(CsvFormatError::BadDelimiter(c)),
    }
}

fn dialect_bytes(
    delimiter: Option<char>,
    quote: Option<char>,
    quote_disabled: bool,
) -> Result<(u8, Option<u8>), CsvFormatError> {
    let delimiter = delimiter_byte(delimiter)?;
    if matches!(delimiter, b'\r' | b'\n' | 0) {
        return Err(CsvFormatError::BadDelimiter(delimiter as char));
    }
    if quote_disabled {
        if quote.is_some() {
            return Err(CsvFormatError::ConflictingQuoteSettings);
        }
        return Ok((delimiter, None));
    }
    let quote = quote.unwrap_or('"');
    if !quote.is_ascii_graphic() {
        return Err(CsvFormatError::BadQuote(quote));
    }
    if delimiter == quote as u8 {
        return Err(CsvFormatError::DelimiterQuoteConflict);
    }
    Ok((delimiter, Some(quote as u8)))
}

fn row_fields(schema: &SchemaNode) -> Result<Vec<(&str, ScalarType)>, CsvFormatError> {
    if schema.repeating {
        return Err(CsvFormatError::UnsupportedSchema);
    }
    match &schema.kind {
        SchemaKind::Group { children, .. } => children
            .iter()
            .map(|c| match &c.kind {
                SchemaKind::Scalar { ty } if !c.repeating => Ok((c.name.as_str(), *ty)),
                SchemaKind::ScalarUnion { .. } => Err(CsvFormatError::UnsupportedScalarUnion {
                    field: c.name.clone(),
                }),
                _ => Err(CsvFormatError::UnsupportedSchema),
            })
            .collect(),
        SchemaKind::Scalar { .. } | SchemaKind::ScalarUnion { .. } => {
            Err(CsvFormatError::UnsupportedSchema)
        }
    }
}

fn parse_present_value(
    name: &str,
    ty: ScalarType,
    cell: &str,
    row: usize,
) -> Result<Value, CsvFormatError> {
    let bad = || CsvFormatError::Parse {
        row,
        field: name.to_string(),
        expected: ty,
        value: cell.to_string(),
    };
    Ok(match ty {
        ScalarType::String => Value::String(cell.to_string()),
        ScalarType::Int => Value::Int(cell.parse().map_err(|_| bad())?),
        ScalarType::Float => {
            let value = cell.parse::<f64>().map_err(|_| bad())?;
            if !value.is_finite() {
                return Err(bad());
            }
            Value::Float(value)
        }
        ScalarType::Bool => Value::Bool(boolean_lexical(cell).ok_or_else(bad)?),
    })
}

/// Writes one row per [`Instance::Group`] in `rows` to a CSV file, with a
/// header row when `has_headers`. `delimiter` defaults to `,`.
pub fn write(
    path: &Path,
    schema: &SchemaNode,
    rows: &[Instance],
    delimiter: Option<char>,
    has_headers: bool,
) -> Result<(), CsvFormatError> {
    write_with_quote(path, schema, rows, delimiter, None, has_headers)
}

/// Write CSV rows with an explicit single-byte quote character.
pub fn write_with_quote(
    path: &Path,
    schema: &SchemaNode,
    rows: &[Instance],
    delimiter: Option<char>,
    quote: Option<char>,
    has_headers: bool,
) -> Result<(), CsvFormatError> {
    write_with_dialect(path, schema, rows, delimiter, quote, false, has_headers)
}

/// Write CSV rows with optional quote emission disabled.
pub fn write_with_dialect(
    path: &Path,
    schema: &SchemaNode,
    rows: &[Instance],
    delimiter: Option<char>,
    quote: Option<char>,
    quote_disabled: bool,
    has_headers: bool,
) -> Result<(), CsvFormatError> {
    std::fs::write(
        path,
        to_string_with_dialect(schema, rows, delimiter, quote, quote_disabled, has_headers)?,
    )?;
    Ok(())
}

/// Writes one row per [`Instance::Group`] in `rows` as CSV text.
///
/// This is the in-memory equivalent of [`write`], including its delimiter,
/// header, schema validation, and flat-row conventions.
pub fn to_string(
    schema: &SchemaNode,
    rows: &[Instance],
    delimiter: Option<char>,
    has_headers: bool,
) -> Result<String, CsvFormatError> {
    to_string_with_quote(schema, rows, delimiter, None, has_headers)
}

/// Render CSV rows with an explicit single-byte quote character.
pub fn to_string_with_quote(
    schema: &SchemaNode,
    rows: &[Instance],
    delimiter: Option<char>,
    quote: Option<char>,
    has_headers: bool,
) -> Result<String, CsvFormatError> {
    to_string_with_dialect(schema, rows, delimiter, quote, false, has_headers)
}

/// Render CSV rows with optional quote emission disabled. Fields that require
/// quoting to preserve their column or row boundary reject before any output.
pub fn to_string_with_dialect(
    schema: &SchemaNode,
    rows: &[Instance],
    delimiter: Option<char>,
    quote: Option<char>,
    quote_disabled: bool,
    has_headers: bool,
) -> Result<String, CsvFormatError> {
    let fields = row_fields(schema)?;
    let (delimiter, quote) = dialect_bytes(delimiter, quote, quote_disabled)?;
    // Validate and materialize every record before producing output. A
    // shape/type error must not truncate a previously valid output file.
    let records = rows
        .iter()
        .enumerate()
        .map(|(row, instance)| format_row(row, instance, &fields))
        .collect::<Result<Vec<_>, _>>()?;
    if quote_disabled {
        for (name, _) in &fields {
            if has_headers && requires_quoting(name, delimiter) {
                return Err(CsvFormatError::UnquotedHeaderBoundary {
                    field: (*name).to_string(),
                });
            }
        }
        for (row, record) in records.iter().enumerate() {
            if record.len() == 1 && record[0].is_empty() {
                return Err(CsvFormatError::UnquotedSingleEmptyRow { row });
            }
            for ((field, _), value) in fields.iter().zip(record) {
                if requires_quoting(value, delimiter) {
                    return Err(CsvFormatError::UnquotedFieldBoundary {
                        row,
                        field: (*field).to_string(),
                    });
                }
            }
        }
    }
    let mut writer = csv::WriterBuilder::new()
        .delimiter(delimiter)
        .quote(quote.unwrap_or(b'"'))
        .quote_style(if quote_disabled {
            csv::QuoteStyle::Never
        } else {
            csv::QuoteStyle::Necessary
        })
        .from_writer(Vec::new());
    if has_headers {
        writer.write_record(fields.iter().map(|(n, _)| *n))?;
    }
    for record in records {
        writer.write_record(record)?;
    }
    writer.flush()?;
    let bytes = writer.into_inner().map_err(|error| error.into_error())?;
    String::from_utf8(bytes)
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error).into())
}

fn requires_quoting(value: &str, delimiter: u8) -> bool {
    value.contains(delimiter as char) || value.contains(['\r', '\n'])
}

fn format_row(
    row: usize,
    instance: &Instance,
    schema_fields: &[(&str, ScalarType)],
) -> Result<Vec<String>, CsvFormatError> {
    let Instance::Group(instance_fields) = instance else {
        return Err(CsvFormatError::RowShape {
            row,
            got: instance_type_name(instance),
        });
    };

    for (index, (name, _)) in instance_fields.iter().enumerate() {
        if !schema_fields
            .iter()
            .any(|(schema_name, _)| schema_name == name)
        {
            return Err(CsvFormatError::UnexpectedField {
                row,
                field: name.clone(),
            });
        }
        if instance_fields[..index]
            .iter()
            .any(|(previous, _)| previous == name)
        {
            return Err(CsvFormatError::DuplicateField {
                row,
                field: name.clone(),
            });
        }
    }

    schema_fields
        .iter()
        .map(|(name, ty)| {
            let value = instance_fields
                .iter()
                .find(|(instance_name, _)| instance_name == name)
                .ok_or_else(|| CsvFormatError::MissingField {
                    row,
                    field: (*name).to_string(),
                })?;
            let Instance::Scalar(value) = &value.1 else {
                return Err(value_type_error(
                    row,
                    name,
                    *ty,
                    instance_type_name(&value.1),
                ));
            };
            format_value(row, name, *ty, value)
        })
        .collect()
}

fn format_value(
    row: usize,
    field: &str,
    ty: ScalarType,
    value: &Value,
) -> Result<String, CsvFormatError> {
    let incompatible = || value_type_error(row, field, ty, value.type_name());
    match (ty, value) {
        (_, Value::Null | Value::JsonNull(_)) => Ok(String::new()),
        (ScalarType::String, Value::Bool(value)) => Ok(value.to_string()),
        (ScalarType::String, Value::Int(value)) => Ok(value.to_string()),
        (ScalarType::String, Value::Float(value)) if value.is_finite() => Ok(value.to_string()),
        (ScalarType::String, Value::Float(_)) => {
            Err(value_type_error(row, field, ty, "non-finite float"))
        }
        (ScalarType::String, Value::String(value)) => Ok(value.clone()),
        (ScalarType::Int, Value::Int(value)) => Ok(value.to_string()),
        (ScalarType::Int, Value::String(value)) => value
            .trim()
            .parse::<i64>()
            .map(|value| value.to_string())
            .map_err(|_| incompatible()),
        (ScalarType::Float, Value::Float(value)) if value.is_finite() => Ok(value.to_string()),
        (ScalarType::Float, Value::Float(_)) => {
            Err(value_type_error(row, field, ty, "non-finite float"))
        }
        (ScalarType::Float, Value::Int(value)) if exact_f64(*value).is_some() => {
            Ok(value.to_string())
        }
        (ScalarType::Float, Value::Int(_)) => Err(value_type_error(
            row,
            field,
            ty,
            "int outside the exact f64 range",
        )),
        (ScalarType::Float, Value::String(value)) => value
            .trim()
            .parse::<f64>()
            .ok()
            .filter(|value| value.is_finite())
            .map(|value| value.to_string())
            .ok_or_else(incompatible),
        (ScalarType::Bool, Value::Bool(value)) => Ok(value.to_string()),
        (ScalarType::Bool, Value::String(value)) => boolean_lexical(value)
            .map(|value| value.to_string())
            .ok_or_else(incompatible),
        _ => Err(incompatible()),
    }
}

fn boolean_lexical(value: &str) -> Option<bool> {
    match value.trim() {
        "true" | "1" => Some(true),
        "false" | "0" => Some(false),
        _ => None,
    }
}

fn exact_f64(value: i64) -> Option<f64> {
    let magnitude = value.unsigned_abs();
    if magnitude == 0 {
        return Some(0.0);
    }
    let significant_bits = u64::BITS - magnitude.leading_zeros() - magnitude.trailing_zeros();
    (significant_bits <= f64::MANTISSA_DIGITS).then_some(value as f64)
}

fn value_type_error(
    row: usize,
    field: &str,
    expected: ScalarType,
    got: &'static str,
) -> CsvFormatError {
    CsvFormatError::ValueType {
        row,
        field: field.to_string(),
        expected,
        got,
    }
}

fn instance_type_name(instance: &Instance) -> &'static str {
    match instance {
        Instance::Scalar(value) => value.type_name(),
        Instance::Group(_) => "group",
        Instance::Repeated(_) => "repeated",
        Instance::MappedSequence(_) => "mapped sequence",
        Instance::DocumentSet(_) => "document set",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_file(tag: &str, contents: &str) -> std::path::PathBuf {
        let path = std::env::temp_dir().join(format!(
            "ferrule-format-csv-sample-{tag}-{}.csv",
            std::process::id()
        ));
        std::fs::write(&path, contents).unwrap();
        path
    }

    #[test]
    fn sample_preserves_quoted_headers_and_cells() {
        let path = sample_file("quotes", "\"Full, name\",age\n\"Doe, Jane\",29\n");
        let preview = sample(&path, None, true).unwrap();
        std::fs::remove_file(path).unwrap();
        assert_eq!(preview.columns, ["Full, name", "age"]);
        assert_eq!(preview.rows.len(), 1);
        assert_eq!(preview.rows[0], ["Doe, Jane", "29"]);
    }

    #[test]
    fn sample_handles_headerless_alternate_delimiter_and_wide_rows() {
        let path = sample_file("semicolon", "Jane;29\nJohn;30;yes\n");
        let preview = sample(&path, Some(';'), false).unwrap();
        std::fs::remove_file(path).unwrap();
        assert_eq!(preview.columns, ["Column 1", "Column 2", "Column 3"]);
        assert_eq!(preview.rows.len(), 2);
        assert_eq!(preview.rows[0], ["Jane", "29"]);
        assert_eq!(preview.rows[1], ["John", "30", "yes"]);
    }

    #[test]
    fn sample_reports_byte_cap_for_truncated_quoted_row() {
        let path = sample_file(
            "large-row",
            &format!("name\n\"{}", "x".repeat(MAX_SAMPLE_BYTES)),
        );
        let error = sample(&path, None, true).unwrap_err();
        std::fs::remove_file(path).unwrap();
        assert!(matches!(error, CsvFormatError::SampleTooLarge));
    }

    fn schema() -> SchemaNode {
        SchemaNode::group(
            "row",
            vec![
                SchemaNode::scalar("name", ScalarType::String),
                SchemaNode::scalar("age", ScalarType::Int),
            ],
        )
    }

    #[test]
    fn text_io_roundtrips_with_headers() {
        let row = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane".into())),
            ),
            ("age".into(), Instance::Scalar(Value::Int(29))),
        ]);

        let text = to_string(&schema(), std::slice::from_ref(&row), None, true).unwrap();
        let read_back = from_str(&text, &schema(), None, true).unwrap();

        assert_eq!(text, "name,age\nJane,29\n");
        assert_eq!(read_back, vec![row]);
    }

    #[test]
    fn custom_quote_roundtrips_delimiters_and_escaped_quotes() {
        let row = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("O'Neil, Jr.".into())),
            ),
            ("age".into(), Instance::Scalar(Value::Int(29))),
        ]);
        let text = to_string_with_quote(
            &schema(),
            std::slice::from_ref(&row),
            None,
            Some('\''),
            true,
        )
        .unwrap();
        assert_eq!(text, "name,age\n'O''Neil, Jr.',29\n");
        assert_eq!(
            from_str_with_quote(&text, &schema(), None, Some('\''), true).unwrap(),
            vec![row]
        );
    }

    #[test]
    fn disabled_quoting_treats_quote_characters_as_data() {
        let text = "name;age\n\"Jane\";29\n";
        let rows = from_str_with_dialect(text, &schema(), Some(';'), None, true, true).unwrap();
        assert_eq!(
            rows[0].field("name").and_then(Instance::as_scalar),
            Some(&Value::String("\"Jane\"".into()))
        );
        assert_eq!(
            to_string_with_dialect(&schema(), &rows, Some(';'), None, true, true).unwrap(),
            text
        );
    }

    #[test]
    fn disabled_quoting_rejects_ambiguous_output_before_writing() {
        let row = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane; Jr.".into())),
            ),
            ("age".into(), Instance::Scalar(Value::Int(29))),
        ]);
        assert!(matches!(
            to_string_with_dialect(&schema(), &[row], Some(';'), None, true, true),
            Err(CsvFormatError::UnquotedFieldBoundary { field, .. }) if field == "name"
        ));
        assert!(matches!(
            from_str_with_dialect("", &schema(), None, Some('\''), true, true),
            Err(CsvFormatError::ConflictingQuoteSettings)
        ));
    }

    #[test]
    fn invalid_custom_quotes_reject_before_parsing_or_writing() {
        assert!(matches!(
            from_str_with_quote("", &schema(), None, Some('é'), true),
            Err(CsvFormatError::BadQuote('é'))
        ));
        assert!(matches!(
            from_str_with_quote("", &schema(), None, Some('\t'), true),
            Err(CsvFormatError::BadQuote('\t'))
        ));
        assert!(matches!(
            to_string_with_quote(&schema(), &[], Some('|'), Some('|'), false),
            Err(CsvFormatError::DelimiterQuoteConflict)
        ));
    }

    #[test]
    fn column_count_mismatch_is_reported() {
        let dir = std::env::temp_dir();
        let path = dir.join(format!(
            "ferrule_format_csv_test_bad_{}.csv",
            std::process::id()
        ));
        std::fs::write(&path, "name,age,extra\nJane,29,x\n").unwrap();

        let err = read(&path, &schema(), None, true).unwrap_err();
        std::fs::remove_file(&path).unwrap();
        assert!(matches!(
            err,
            CsvFormatError::ColumnCount {
                expected: 2,
                got: 3,
                ..
            }
        ));
    }

    #[test]
    fn missing_trailing_columns_are_null() {
        let rows = from_str("Jane,29\nJohn\n", &schema(), None, false).unwrap();

        assert_eq!(
            rows,
            vec![
                Instance::Group(vec![
                    (
                        "name".into(),
                        Instance::Scalar(Value::String("Jane".into())),
                    ),
                    ("age".into(), Instance::Scalar(Value::Int(29))),
                ]),
                Instance::Group(vec![
                    (
                        "name".into(),
                        Instance::Scalar(Value::String("John".into())),
                    ),
                    ("age".into(), Instance::Scalar(Value::Null)),
                ]),
            ]
        );
    }

    #[test]
    fn text_io_roundtrips_without_headers() {
        let row = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane".into())),
            ),
            ("age".into(), Instance::Scalar(Value::Int(29))),
        ]);

        let text = to_string(&schema(), std::slice::from_ref(&row), None, false).unwrap();
        let read_back = from_str(&text, &schema(), None, false).unwrap();

        assert_eq!(text, "Jane,29\n");
        assert_eq!(read_back, vec![row]);
    }

    #[test]
    fn text_io_roundtrips_a_custom_delimiter_and_quoted_value() {
        let row = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane;Doe".into())),
            ),
            ("age".into(), Instance::Scalar(Value::Int(29))),
        ]);

        let text = to_string(&schema(), std::slice::from_ref(&row), Some(';'), true).unwrap();
        let read_back = from_str(&text, &schema(), Some(';'), true).unwrap();

        assert_eq!(text, "name;age\n\"Jane;Doe\";29\n");
        // The value containing the delimiter must be quoted, not split.
        assert_eq!(read_back, vec![row]);
    }

    #[test]
    fn write_rejects_incompatible_typed_strings_without_truncating_output() {
        let path = std::env::temp_dir().join(format!(
            "ferrule_format_csv_test_invalid_value_{}.csv",
            std::process::id()
        ));
        std::fs::write(&path, "existing output\n").unwrap();
        let row = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane".into())),
            ),
            (
                "age".into(),
                Instance::Scalar(Value::String("not a number".into())),
            ),
        ]);

        let error = write(&path, &schema(), &[row], None, true).unwrap_err();
        let unchanged = std::fs::read_to_string(&path).unwrap();
        std::fs::remove_file(&path).unwrap();

        assert!(matches!(
            error,
            CsvFormatError::ValueType {
                row: 0,
                field,
                expected: ScalarType::Int,
                got: "string",
            } if field == "age"
        ));
        assert_eq!(unchanged, "existing output\n");
    }

    #[test]
    fn write_rejects_non_group_rows() {
        let path = std::env::temp_dir().join(format!(
            "ferrule_format_csv_test_scalar_row_{}.csv",
            std::process::id()
        ));

        let error = write(
            &path,
            &schema(),
            &[Instance::Scalar(Value::String("Jane,29".into()))],
            None,
            true,
        )
        .unwrap_err();

        assert!(matches!(
            error,
            CsvFormatError::RowShape {
                row: 0,
                got: "string"
            }
        ));
        assert!(!path.exists());

        let error = write(
            &path,
            &schema(),
            &[Instance::MappedSequence(Vec::new())],
            None,
            true,
        )
        .unwrap_err();
        assert!(matches!(
            error,
            CsvFormatError::RowShape {
                row: 0,
                got: "mapped sequence"
            }
        ));
        assert!(!path.exists());
    }

    #[test]
    fn write_rejects_missing_and_non_scalar_fields() {
        let path = std::env::temp_dir().join(format!(
            "ferrule_format_csv_test_bad_fields_{}.csv",
            std::process::id()
        ));
        let missing = Instance::Group(vec![(
            "name".into(),
            Instance::Scalar(Value::String("Jane".into())),
        )]);
        let error = write(&path, &schema(), &[missing], None, false).unwrap_err();
        assert!(matches!(
            error,
            CsvFormatError::MissingField { row: 0, field } if field == "age"
        ));

        let nested = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane".into())),
            ),
            ("age".into(), Instance::Group(Vec::new())),
        ]);
        let error = write(&path, &schema(), &[nested], None, false).unwrap_err();
        assert!(matches!(
            error,
            CsvFormatError::ValueType {
                row: 0,
                field,
                expected: ScalarType::Int,
                got: "group",
            } if field == "age"
        ));

        let mapped = Instance::Group(vec![
            (
                "name".into(),
                Instance::Scalar(Value::String("Jane".into())),
            ),
            ("age".into(), Instance::MappedSequence(Vec::new())),
        ]);
        let error = write(&path, &schema(), &[mapped], None, false).unwrap_err();
        assert!(matches!(
            error,
            CsvFormatError::ValueType {
                row: 0,
                field,
                expected: ScalarType::Int,
                got: "mapped sequence",
            } if field == "age"
        ));
        assert!(!path.exists());
    }

    #[test]
    fn null_cells_roundtrip_for_all_scalar_types() {
        let path = std::env::temp_dir().join(format!(
            "ferrule_format_csv_test_nulls_{}.csv",
            std::process::id()
        ));
        let schema = SchemaNode::group(
            "row",
            vec![
                SchemaNode::scalar("text", ScalarType::String),
                SchemaNode::scalar("integer", ScalarType::Int),
                SchemaNode::scalar("number", ScalarType::Float),
                SchemaNode::scalar("boolean", ScalarType::Bool),
            ],
        );
        let row = Instance::Group(
            ["text", "integer", "number", "boolean"]
                .into_iter()
                .map(|name| (name.to_string(), Instance::Scalar(Value::Null)))
                .collect(),
        );

        write(&path, &schema, std::slice::from_ref(&row), None, true).unwrap();
        let read_back = read(&path, &schema, None, true).unwrap();
        std::fs::remove_file(&path).unwrap();

        assert_eq!(read_back, vec![row]);
    }

    #[test]
    fn boolean_columns_accept_word_and_numeric_lexicals() {
        let schema = SchemaNode::group(
            "row",
            vec![
                SchemaNode::scalar("left", ScalarType::Bool),
                SchemaNode::scalar("right", ScalarType::Bool),
            ],
        );
        assert_eq!(
            from_str("1,false\n0,true\n", &schema, None, false).unwrap(),
            vec![
                Instance::Group(vec![
                    ("left".into(), Instance::Scalar(Value::Bool(true))),
                    ("right".into(), Instance::Scalar(Value::Bool(false))),
                ]),
                Instance::Group(vec![
                    ("left".into(), Instance::Scalar(Value::Bool(false))),
                    ("right".into(), Instance::Scalar(Value::Bool(true))),
                ]),
            ]
        );

        let row = Instance::Group(vec![
            ("left".into(), Instance::Scalar(Value::String(" 1 ".into()))),
            ("right".into(), Instance::Scalar(Value::String("0".into()))),
        ]);
        assert_eq!(
            to_string(&schema, &[row], None, false).unwrap(),
            "true,false\n"
        );
        assert!(matches!(
            from_str("yes,no\n", &schema, None, false),
            Err(CsvFormatError::Parse {
                row: 0,
                expected: ScalarType::Bool,
                ..
            })
        ));
    }

    #[test]
    fn read_rejects_non_finite_float_cells() {
        let path = std::env::temp_dir().join(format!(
            "ferrule_format_csv_test_non_finite_{}.csv",
            std::process::id()
        ));
        let schema =
            SchemaNode::group("row", vec![SchemaNode::scalar("number", ScalarType::Float)]);

        for value in ["NaN", "inf", "1e999"] {
            std::fs::write(&path, format!("{value}\n")).unwrap();
            assert!(matches!(
                read(&path, &schema, None, false),
                Err(CsvFormatError::Parse {
                    row: 0,
                    ref field,
                    expected: ScalarType::Float,
                    ..
                }) if field == "number"
            ));
        }
        std::fs::remove_file(path).unwrap();
    }
}
