//! Deterministic Rust source generation for backend-neutral ferrule programs.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::fmt;

use codegen::{
    AggregateFunction, AggregateValue, ArtifactPath, ArtifactPathError, ArtifactSet,
    ArtifactSetError, Binding, Expression, GeneratedFile, GeneratedSequence, IterationOutput,
    IterationPlan, IterationSource, Program, ProgramValidationError, SequenceWindow,
    SortFilterOrder, TargetConstruction, TargetScope, validate_program,
};
use ir::{ScalarType, Value};
use mapping::NodeId;

/// How a generated Cargo project locates ferrule's small Rust runtime.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RuntimeDependency {
    Path(String),
    Version(String),
    Git {
        repository: String,
        revision: String,
    },
}

/// Rust project generation settings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Options {
    pub package_name: String,
    pub runtime_dependency: RuntimeDependency,
}

/// Failure to render a complete Rust project.
#[derive(Debug)]
pub enum EmitError {
    InvalidProgram(ProgramValidationError),
    InvalidPackageName(String),
    NonFiniteFloat { node: NodeId },
    ArtifactPath(ArtifactPathError),
    ArtifactSet(ArtifactSetError),
}

impl fmt::Display for EmitError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidProgram(error) => error.fmt(formatter),
            Self::InvalidPackageName(name) => {
                write!(formatter, "invalid generated Rust package name {name:?}")
            }
            Self::NonFiniteFloat { node } => {
                write!(
                    formatter,
                    "graph node {node} contains a non-finite float literal"
                )
            }
            Self::ArtifactPath(error) => error.fmt(formatter),
            Self::ArtifactSet(error) => error.fmt(formatter),
        }
    }
}

impl std::error::Error for EmitError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::InvalidProgram(error) => Some(error),
            Self::ArtifactPath(error) => Some(error),
            Self::ArtifactSet(error) => Some(error),
            Self::InvalidPackageName(_) | Self::NonFiniteFloat { .. } => None,
        }
    }
}

impl From<ProgramValidationError> for EmitError {
    fn from(error: ProgramValidationError) -> Self {
        Self::InvalidProgram(error)
    }
}

impl From<ArtifactPathError> for EmitError {
    fn from(error: ArtifactPathError) -> Self {
        Self::ArtifactPath(error)
    }
}

impl From<ArtifactSetError> for EmitError {
    fn from(error: ArtifactSetError) -> Self {
        Self::ArtifactSet(error)
    }
}

/// Emits one buildable Rust library project.
pub fn emit(program: &Program, options: &Options) -> Result<ArtifactSet, EmitError> {
    validate_program(program)?;
    if !valid_package_name(&options.package_name) {
        return Err(EmitError::InvalidPackageName(options.package_name.clone()));
    }
    let manifest = render_manifest(options);
    let source = render_source(program)?;
    ArtifactSet::new([
        GeneratedFile::new(ArtifactPath::new("Cargo.toml")?, manifest),
        GeneratedFile::new(ArtifactPath::new("src/lib.rs")?, source),
    ])
    .map_err(EmitError::from)
}

fn valid_package_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        && name
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphabetic())
}

fn render_manifest(options: &Options) -> String {
    let dependency = match &options.runtime_dependency {
        RuntimeDependency::Path(path) => format!("path = {}", toml_string(path)),
        RuntimeDependency::Version(version) => format!("version = {}", toml_string(version)),
        RuntimeDependency::Git {
            repository,
            revision,
        } => format!(
            "git = {}, rev = {}",
            toml_string(repository),
            toml_string(revision)
        ),
    };
    format!(
        "[package]\nname = {}\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n\n[dependencies]\ncodegen-runtime = {{ {dependency} }}\n",
        toml_string(&options.package_name)
    )
}

fn render_source(program: &Program) -> Result<String, EmitError> {
    let mut source = String::from(
        "// Generated by ferrule. Do not edit.\n\
         use codegen_runtime::{\n\
             AggregateFunction, GeneratedItems, Instance, RecursiveCollectPaths, RuntimeError,\n\
             ScalarType, ScopeContext,\n\
             SequenceWindow, SortDirection, Value, adapt_target_value, aggregate,\n\
             apply_sequence_windows, call, field, generate_sequence, group, item_count, repeated,\n\
             recursive_collect, recursive_sequence_parameter, require_bool, scalar,\n\
             sort_candidates, tokenize, tokenize_by_length,\n\
         };\n\n",
    );
    source.push_str(
        "pub fn execute(source: &Instance) -> Result<Instance, RuntimeError> {\n    scope_root(&ScopeContext::new(source))\n}\n\n",
    );

    for node in &program.expressions {
        source.push_str(&render_expression(node.id, &node.expression)?);
    }

    let mut scopes = Vec::new();
    collect_scopes(&program.root, "scope_root".to_string(), &mut scopes);
    for (name, scope, child_names) in scopes {
        source.push_str(&render_scope(&name, scope, &child_names)?);
    }
    Ok(source)
}

fn render_expression(id: NodeId, expression: &Expression) -> Result<String, EmitError> {
    let body = match expression {
        Expression::SourceField { frame, path } => {
            let path = path
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            match frame {
                Some(frame) => {
                    let frame = frame
                        .iter()
                        .map(|segment| rust_string(segment))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!(
                        "context.resolve_scalar_in_frame(&[{frame}], &[{path}]).map_err(RuntimeError::from)"
                    )
                }
                None => {
                    format!("context.resolve_scalar(&[{path}]).map_err(RuntimeError::from)")
                }
            }
        }
        Expression::Position { collection } => {
            let collection = collection
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            format!("Ok(Value::Int(context.position(&[{collection}]) as i64))")
        }
        Expression::Const { value } => {
            format!("Ok({})", rust_value(id, value)?)
        }
        Expression::Call { function, args } => {
            let mut body = format!(
                "{{\n        let mut args = Vec::with_capacity({});\n",
                args.len()
            );
            for arg in args {
                body.push_str(&format!("        args.push(expression_{arg}(context)?);\n"));
            }
            body.push_str(&format!(
                "        call({}, &args)\n    }}",
                rust_string(function.as_str())
            ));
            body
        }
        Expression::If {
            condition,
            then,
            else_,
        } => format!(
            "{{\n        let condition = expression_{condition}(context)?;\n        if require_bool({condition}, condition)? {{\n            expression_{then}(context)\n        }} else {{\n            expression_{else_}(context)\n        }}\n    }}"
        ),
        Expression::Aggregate {
            function,
            collection,
            value,
            arg,
        } => {
            let collection = collection
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            let mut body = format!(
                "{{\n        let item_contexts = context.aggregate_items(&[{collection}]);\n        let mut values = Vec::with_capacity(item_contexts.len());\n        for item_context in item_contexts {{\n"
            );
            match value {
                AggregateValue::Path(path) => {
                    let path = path
                        .iter()
                        .map(|segment| rust_string(segment))
                        .collect::<Vec<_>>()
                        .join(", ");
                    body.push_str(&format!(
                        "            values.push(item_context.aggregate_current_scalar(&[{path}]));\n"
                    ));
                }
                AggregateValue::Expression(expression) => body.push_str(&format!(
                    "            values.push(expression_{expression}(&item_context)?);\n"
                )),
            }
            body.push_str("        }\n");
            match arg {
                Some(arg) => body.push_str(&format!(
                    "        let arg = Some(expression_{arg}(context)?);\n"
                )),
                None => body.push_str("        let arg = None;\n"),
            }
            body.push_str(&format!(
                "        aggregate(AggregateFunction::{}, &values, arg)\n    }}",
                aggregate_function_name(*function)
            ));
            body
        }
        Expression::SequenceExists {
            sequence,
            predicate,
        } => {
            let mut body = String::from("{\n");
            render_generated_values(sequence, "        ", &mut body);
            body.push_str(&format!(
                "        let generated_items = GeneratedItems::new(sequence_values);\n        for item_context in context.generated_item_contexts(&generated_items) {{\n            let predicate = expression_{predicate}(&item_context)?;\n            if require_bool({predicate}, predicate)? {{\n                return Ok(Value::Bool(true));\n            }}\n        }}\n        Ok(Value::Bool(false))\n    }}"
            ));
            body
        }
        Expression::SequenceItemAt { sequence, index } => {
            let mut body = String::from("{\n");
            render_generated_values(sequence, "        ", &mut body);
            body.push_str(&format!(
                "        let index = expression_{index}(context)?;\n        aggregate(AggregateFunction::ItemAt, &sequence_values, Some(index))\n    }}"
            ));
            body
        }
    };
    Ok(format!(
        "fn expression_{id}(context: &ScopeContext<'_>) -> Result<Value, RuntimeError> {{\n    let _ = context;\n    {body}\n}}\n\n"
    ))
}

const fn aggregate_function_name(function: AggregateFunction) -> &'static str {
    match function {
        AggregateFunction::Count => "Count",
        AggregateFunction::Sum => "Sum",
        AggregateFunction::Avg => "Avg",
        AggregateFunction::Min => "Min",
        AggregateFunction::Max => "Max",
        AggregateFunction::Join => "Join",
        AggregateFunction::ItemAt => "ItemAt",
    }
}

fn collect_scopes<'a>(
    scope: &'a TargetScope,
    name: String,
    output: &mut Vec<(String, &'a TargetScope, Vec<String>)>,
) {
    let child_names = scope
        .children
        .iter()
        .enumerate()
        .map(|(index, _)| format!("{name}_{index}"))
        .collect::<Vec<_>>();
    output.push((name, scope, child_names.clone()));
    for (child, child_name) in scope.children.iter().zip(child_names) {
        collect_scopes(child, child_name, output);
    }
}

fn render_scope(
    name: &str,
    scope: &TargetScope,
    child_names: &[String],
) -> Result<String, EmitError> {
    let mut output =
        format!("fn {name}(context: &ScopeContext<'_>) -> Result<Instance, RuntimeError> {{\n");
    if let Some(iteration) = &scope.iteration {
        output.push_str(&render_iteration_scope(scope, iteration, child_names));
    } else {
        output.push_str(&render_scope_item(scope, child_names, "    ", "context"));
        if scope.repeating {
            output.push_str("    Ok(repeated([output]))\n");
        } else {
            output.push_str("    Ok(output)\n");
        }
    }
    output.push_str("}\n\n");
    Ok(output)
}

fn render_iteration_scope(
    scope: &TargetScope,
    iteration: &IterationPlan,
    child_names: &[String],
) -> String {
    let mut output = String::new();
    let sort = iteration.sort();
    let filter_before_sort = iteration.filter().is_some()
        && sort.is_some_and(|sort| sort.filter_order() == SortFilterOrder::FilterThenSort);
    let has_windows =
        !iteration.windows().is_empty() || iteration.output() == IterationOutput::First;
    let renumber_output = iteration.filter().is_some() || sort.is_some() || has_windows;

    render_iteration_candidates(iteration.input(), &mut output);
    if filter_before_sort {
        render_prefilter(iteration.filter(), &mut output);
    }
    if let Some(sort) = sort {
        let keys = sort.keys().collect::<Vec<_>>();
        output.push_str("    let mut keyed_candidates = Vec::with_capacity(candidates.len());\n");
        output.push_str("    for candidate in candidates {\n        let keys = [\n");
        for key in &keys {
            output.push_str(&format!(
                "            expression_{}(&candidate)?,\n",
                key.expression
            ));
        }
        output.push_str("        ];\n        keyed_candidates.push((candidate, keys));\n    }\n");
        output.push_str("    candidates = sort_candidates(keyed_candidates, [\n");
        for key in &keys {
            let direction = if key.descending {
                "Descending"
            } else {
                "Ascending"
            };
            output.push_str(&format!("        SortDirection::{direction},\n"));
        }
        output.push_str(
            "    ]);\n    candidates = candidates\n        .into_iter()\n        .enumerate()\n        .map(|(index, candidate)| candidate.with_compact_last_position(index + 1))\n        .collect();\n",
        );
    }

    render_windows(iteration, &mut output);
    if has_windows && !filter_before_sort {
        render_prefilter(iteration.filter(), &mut output);
    }
    if has_windows {
        output.push_str("    candidates = apply_sequence_windows(candidates, &windows);\n");
    }

    output.push_str("    let mut outputs = Vec::with_capacity(candidates.len());\n");
    output.push_str("    for item_context in candidates {\n");
    if !filter_before_sort
        && !has_windows
        && let Some(filter) = iteration.filter()
    {
        output.push_str(&format!(
            "        let filter_value = expression_{filter}(&item_context)?;\n        if !require_bool({filter}, filter_value)? {{\n            continue;\n        }}\n"
        ));
    }
    let item_context = if renumber_output {
        output.push_str(
            "        let output_context = item_context.with_compact_last_position(outputs.len() + 1);\n",
        );
        "&output_context"
    } else {
        "&item_context"
    };
    output.push_str(&render_scope_item(
        scope,
        child_names,
        "        ",
        item_context,
    ));
    output.push_str("        outputs.push(output);\n    }\n");
    match iteration.output() {
        IterationOutput::Repeated => output.push_str("    Ok(repeated(outputs))\n"),
        IterationOutput::MappedSequence => {
            output.push_str("    Ok(Instance::MappedSequence(outputs))\n");
        }
        IterationOutput::First => output
            .push_str("    Ok(outputs.into_iter().next().unwrap_or_else(|| group(Vec::new())))\n"),
    }
    output
}

fn render_iteration_candidates(input: &IterationSource, output: &mut String) {
    match input {
        IterationSource::Source(source) => {
            let path = source
                .path()
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "    let mut candidates = context.walk_source(&[{path}]);\n"
            ));
        }
        IterationSource::Generated(sequence) => {
            render_generated_values(sequence, "    ", output);
            output.push_str(
                "    let generated_items = GeneratedItems::new(sequence_values);\n    let mut candidates = context.generated_items(&generated_items);\n",
            );
        }
    }
}

fn render_generated_values(sequence: &GeneratedSequence, indent: &str, output: &mut String) {
    match sequence {
        GeneratedSequence::Tokenize {
            input, delimiter, ..
        } => output.push_str(&format!(
            "{indent}let sequence_input = expression_{input}(context)?;\n{indent}let sequence_values = if sequence_input == Value::Null {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_parameter = expression_{delimiter}(context)?;\n{indent}    if sequence_parameter == Value::Null {{\n{indent}        Vec::new()\n{indent}    }} else {{\n{indent}        tokenize(sequence_input, sequence_parameter)?\n{indent}    }}\n{indent}}};\n"
        )),
        GeneratedSequence::TokenizeByLength { input, length, .. } => output.push_str(&format!(
            "{indent}let sequence_input = expression_{input}(context)?;\n{indent}let sequence_values = if sequence_input == Value::Null {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_parameter = expression_{length}(context)?;\n{indent}    if sequence_parameter == Value::Null {{\n{indent}        Vec::new()\n{indent}    }} else {{\n{indent}        tokenize_by_length(sequence_input, sequence_parameter)?\n{indent}    }}\n{indent}}};\n"
        )),
        GeneratedSequence::RecursiveCollect {
            collection,
            children,
            descent_value,
            values,
            value,
            prefix,
            separator,
            ..
        } => {
            let path = |segments: &[String]| {
                segments
                    .iter()
                    .map(|segment| rust_string(segment))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let collection = path(collection);
            let children = path(children);
            let descent_value = path(descent_value);
            let values = path(values);
            let value = path(value);
            output.push_str(&format!(
                "{indent}let sequence_prefix = recursive_sequence_parameter(expression_{prefix}(context)?)?;\n{indent}let sequence_separator = recursive_sequence_parameter(expression_{separator}(context)?)?;\n{indent}let sequence_values = recursive_collect(\n{indent}    context,\n{indent}    RecursiveCollectPaths {{\n{indent}        collection: &[{collection}],\n{indent}        children: &[{children}],\n{indent}        descent_value: &[{descent_value}],\n{indent}        values: &[{values}],\n{indent}        value: &[{value}],\n{indent}    }},\n{indent}    &sequence_prefix,\n{indent}    &sequence_separator,\n{indent})?;\n"
            ));
        }
        GeneratedSequence::Range {
            from: Some(from),
            to,
            ..
        } => output.push_str(&format!(
            "{indent}let sequence_from = expression_{from}(context)?;\n{indent}let sequence_values = if sequence_from == Value::Null {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_to = expression_{to}(context)?;\n{indent}    if sequence_to == Value::Null {{\n{indent}        Vec::new()\n{indent}    }} else {{\n{indent}        generate_sequence(Some(sequence_from), sequence_to)?\n{indent}    }}\n{indent}}};\n"
        )),
        GeneratedSequence::Range { from: None, to, .. } => output.push_str(&format!(
            "{indent}let sequence_to = expression_{to}(context)?;\n{indent}let sequence_values = if sequence_to == Value::Null {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    generate_sequence(None, sequence_to)?\n{indent}}};\n"
        )),
    }
}

fn render_prefilter(filter: Option<NodeId>, output: &mut String) {
    let Some(filter) = filter else {
        return;
    };
    output.push_str(&format!(
        "    let mut filtered = Vec::with_capacity(candidates.len());\n    for candidate in candidates {{\n        let filter_value = expression_{filter}(&candidate)?;\n        if require_bool({filter}, filter_value)? {{\n            filtered.push(candidate);\n        }}\n    }}\n    candidates = filtered;\n"
    ));
}

fn render_windows(iteration: &IterationPlan, output: &mut String) {
    let has_windows =
        !iteration.windows().is_empty() || iteration.output() == IterationOutput::First;
    if !has_windows {
        return;
    }
    output.push_str(&format!(
        "    let mut windows = Vec::with_capacity({});\n",
        iteration.windows().len() + usize::from(iteration.output() == IterationOutput::First)
    ));
    for (index, window) in iteration.windows().iter().enumerate() {
        match *window {
            SequenceWindow::SkipFirst { count } => {
                render_single_window(index, "count", count, "SkipFirst", output)
            }
            SequenceWindow::First { count } => {
                render_single_window(index, "count", count, "First", output)
            }
            SequenceWindow::From { position } => {
                render_single_window(index, "position", position, "From", output)
            }
            SequenceWindow::Last { count } => {
                render_single_window(index, "count", count, "Last", output)
            }
            SequenceWindow::FromTo { first, last } => {
                output.push_str(&format!(
                    "    let window_{index}_first = item_count({first}, expression_{first}(context)?)?;\n    let window_{index}_last = item_count({last}, expression_{last}(context)?)?;\n    windows.push(SequenceWindow::FromTo {{ first: window_{index}_first, last: window_{index}_last }});\n"
                ));
            }
        }
    }
    if iteration.output() == IterationOutput::First {
        output.push_str("    windows.push(SequenceWindow::First(1));\n");
    }
}

fn render_single_window(
    index: usize,
    label: &str,
    expression: u32,
    kind: &str,
    output: &mut String,
) {
    output.push_str(&format!(
        "    let window_{index}_{label} = item_count({expression}, expression_{expression}(context)?)?;\n    windows.push(SequenceWindow::{kind}(window_{index}_{label}));\n"
    ));
}

fn render_scope_item(
    scope: &TargetScope,
    child_names: &[String],
    indent: &str,
    context: &str,
) -> String {
    let mut output = String::new();
    if let TargetConstruction::Scalar { expression } = scope.construction {
        output.push_str(&format!(
            "{indent}let output = scalar(expression_{expression}({context})?);\n"
        ));
        return output;
    }
    for (index, binding) in scope.bindings.iter().enumerate() {
        output.push_str(&format!(
            "{indent}let value_{index} = adapt_target_value(expression_{}({context})?, ScalarType::{});\n",
            binding.expression,
            scalar_type_name(binding.target_type)
        ));
    }

    let groups = binding_groups(&scope.bindings);
    for (group_index, group) in groups.iter().enumerate() {
        if !group.repeating {
            continue;
        }
        output.push_str(&format!(
            "{indent}let mut repeated_{group_index} = Vec::new();\n"
        ));
        for binding_index in &group.binding_indices {
            output.push_str(&format!(
                "{indent}if value_{binding_index} != Value::Null {{\n{indent}    repeated_{group_index}.push(scalar(value_{binding_index}));\n{indent}}}\n"
            ));
        }
    }

    let mut fields = Vec::new();
    for (group_index, binding_group) in groups.iter().enumerate() {
        let name = rust_string(&binding_group.target_field);
        if binding_group.repeating {
            fields.push(format!("field({name}, repeated(repeated_{group_index}))"));
        } else {
            let index = binding_group.binding_indices[0];
            fields.push(format!("field({name}, scalar(value_{index}))"));
        }
    }
    for (child, child_name) in scope.children.iter().zip(child_names) {
        fields.push(format!(
            "field({}, {child_name}({context})?)",
            rust_string(&child.target_field)
        ));
    }
    if fields.is_empty() {
        output.push_str(&format!("{indent}let output = group(Vec::new());\n"));
    } else {
        output.push_str(&format!("{indent}let output = group([\n"));
        for field in fields {
            output.push_str(&format!("{indent}    {field},\n"));
        }
        output.push_str(&format!("{indent}]);\n"));
    }
    output
}

struct BindingGroup {
    target_field: String,
    repeating: bool,
    binding_indices: Vec<usize>,
}

fn binding_groups(bindings: &[Binding]) -> Vec<BindingGroup> {
    let mut groups = Vec::<BindingGroup>::new();
    let mut indices = BTreeMap::<&str, usize>::new();
    for (binding_index, binding) in bindings.iter().enumerate() {
        if let Some(index) = indices.get(binding.target_field.as_str()).copied() {
            let group = &mut groups[index];
            group.binding_indices.push(binding_index);
        } else {
            indices.insert(&binding.target_field, groups.len());
            groups.push(BindingGroup {
                target_field: binding.target_field.clone(),
                repeating: binding.repeating,
                binding_indices: vec![binding_index],
            });
        }
    }
    groups
}

fn scalar_type_name(value: ScalarType) -> &'static str {
    match value {
        ScalarType::String => "String",
        ScalarType::Int => "Int",
        ScalarType::Float => "Float",
        ScalarType::Bool => "Bool",
    }
}

fn rust_value(node: NodeId, value: &Value) -> Result<String, EmitError> {
    Ok(match value {
        Value::Null => "Value::Null".to_string(),
        Value::XmlNil(_) => "Value::xml_nil()".to_string(),
        Value::Bool(value) => format!("Value::Bool({value})"),
        Value::Int(i64::MIN) => "Value::Int(i64::MIN)".to_string(),
        Value::Int(value) => format!("Value::Int({value}_i64)"),
        Value::Float(value) if value.is_finite() => {
            format!("Value::Float({value:?}_f64)")
        }
        Value::Float(_) => return Err(EmitError::NonFiniteFloat { node }),
        Value::String(value) => format!("Value::String({}.to_string())", rust_string(value)),
    })
}

fn rust_string(value: &str) -> String {
    let escaped = value
        .chars()
        .flat_map(char::escape_default)
        .collect::<String>();
    format!("\"{escaped}\"")
}

fn toml_string(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\u{8}' => output.push_str("\\b"),
            '\t' => output.push_str("\\t"),
            '\n' => output.push_str("\\n"),
            '\u{c}' => output.push_str("\\f"),
            '\r' => output.push_str("\\r"),
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            character if character.is_ascii() && !character.is_control() => {
                output.push(character);
            }
            character if (character as u32) <= 0xffff => {
                output.push_str(&format!("\\u{:04X}", character as u32));
            }
            character => output.push_str(&format!("\\U{:08X}", character as u32)),
        }
    }
    output.push('"');
    output
}

#[cfg(test)]
mod tests;
