//! Deterministic Rust source generation for backend-neutral ferrule programs.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::fmt;

use codegen::{
    AggregateFunction, AggregateValue, ArtifactPath, ArtifactPathError, ArtifactSet,
    ArtifactSetError, Binding, Expression, GeneratedFile, GeneratedSequence, GroupingPlan,
    InnerJoin, IterationOutput, IterationPlan, IterationSource, Program, ProgramValidationError,
    RuntimeValue, SequenceWindow, SortFilterOrder, TargetConstruction, TargetScope,
    UserFunctionProgram, validate_program,
};
use ir::{ScalarType, Value};
use mapping::{FunctionId, FunctionParameterId, NodeId};

mod failure;

/// How a generated Cargo project locates ferrule's small Rust runtime.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RuntimeDependency {
    Path(String),
    Version(String),
    Git {
        repository: String,
        revision: String,
    },
}

/// Rust project generation settings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Options {
    pub package_name: String,
    pub runtime_dependency: RuntimeDependency,
}

/// Failure to render a complete Rust project.
#[derive(Debug)]
pub enum EmitError {
    InvalidProgram(ProgramValidationError),
    InvalidPackageName(String),
    SchemaSerialization(String),
    ArtifactPath(ArtifactPathError),
    ArtifactSet(ArtifactSetError),
}

impl fmt::Display for EmitError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidProgram(error) => error.fmt(formatter),
            Self::InvalidPackageName(name) => {
                write!(formatter, "invalid generated Rust package name {name:?}")
            }
            Self::SchemaSerialization(message) => {
                write!(formatter, "cannot serialize embedded XML schema: {message}")
            }
            Self::ArtifactPath(error) => error.fmt(formatter),
            Self::ArtifactSet(error) => error.fmt(formatter),
        }
    }
}

impl std::error::Error for EmitError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::InvalidProgram(error) => Some(error),
            Self::ArtifactPath(error) => Some(error),
            Self::ArtifactSet(error) => Some(error),
            Self::InvalidPackageName(_) | Self::SchemaSerialization(_) => None,
        }
    }
}

impl From<ProgramValidationError> for EmitError {
    fn from(error: ProgramValidationError) -> Self {
        Self::InvalidProgram(error)
    }
}

impl From<ArtifactPathError> for EmitError {
    fn from(error: ArtifactPathError) -> Self {
        Self::ArtifactPath(error)
    }
}

impl From<ArtifactSetError> for EmitError {
    fn from(error: ArtifactSetError) -> Self {
        Self::ArtifactSet(error)
    }
}

/// Emits one buildable Rust library project.
pub fn emit(program: &Program, options: &Options) -> Result<ArtifactSet, EmitError> {
    validate_program(program)?;
    if !valid_package_name(&options.package_name) {
        return Err(EmitError::InvalidPackageName(options.package_name.clone()));
    }
    let manifest = render_manifest(options);
    let source = render_source(program)?;
    ArtifactSet::new([
        GeneratedFile::new(ArtifactPath::new("Cargo.toml")?, manifest),
        GeneratedFile::new(ArtifactPath::new("src/lib.rs")?, source),
    ])
    .map_err(EmitError::from)
}

fn valid_package_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        && name
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphabetic())
}

fn render_manifest(options: &Options) -> String {
    let dependency = match &options.runtime_dependency {
        RuntimeDependency::Path(path) => format!("path = {}", toml_string(path)),
        RuntimeDependency::Version(version) => format!("version = {}", toml_string(version)),
        RuntimeDependency::Git {
            repository,
            revision,
        } => format!(
            "git = {}, rev = {}",
            toml_string(repository),
            toml_string(revision)
        ),
    };
    format!(
        "[package]\nname = {}\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n\n[dependencies]\ncodegen-runtime = {{ {dependency} }}\n\n[workspace]\n",
        toml_string(&options.package_name)
    )
}

fn render_source(program: &Program) -> Result<String, EmitError> {
    let mut source = String::from(
        "// Generated by ferrule. Do not edit.\n\
         #[allow(unused_imports)]\n\
         use codegen_runtime::{\n\
             AggregateFunction, ExecutionContext, GeneratedItems, GroupedItems, InnerJoinKey,\n\
             InnerJoinStage, Instance, RecursiveCollectPaths,\n\
             RuntimeError, RuntimeValue,\n\
             ScalarType, ScopeContext,\n\
             SequenceWindow, SortDirection, Value, adapt_target_value, aggregate,\n\
             adapt_user_function_value, apply_sequence_windows, call,\n\
             collection_find_selected, field, generate_sequence,\n\
             group, item_count, repeated,\n\
             recursive_collect, recursive_sequence_parameter, require_bool, scalar,\n\
             serialize_xml, sort_candidates, tokenize, tokenize_by_length, tokenize_regex, value_map,\n\
             xml_mixed_content, XmlMixedContentReplacement,\n\
         };\n\n",
    );
    source.push_str("pub use codegen_runtime::NamedInput;\n\n");
    source.push_str(
        "#[derive(Clone, Debug, PartialEq)]\n\
         pub struct NamedOutput {\n\
             pub name: &'static str,\n\
             pub instance: Instance,\n\
         }\n\n\
         #[derive(Clone, Debug, PartialEq)]\n\
         pub struct ExecutionOutputs {\n\
             pub primary: Instance,\n\
             pub extras: Vec<NamedOutput>,\n\
         }\n\n",
    );
    source.push_str(
        "pub fn execute(source: &Instance) -> Result<Instance, RuntimeError> {\n\
             Ok(execute_outputs(source)?.primary)\n\
         }\n\n\
         pub fn execute_with_context(\n\
             source: &Instance,\n\
             execution: &ExecutionContext<'_>,\n\
         ) -> Result<Instance, RuntimeError> {\n\
             Ok(execute_outputs_with_context(source, execution)?.primary)\n\
         }\n\n\
         pub fn execute_with_sources(\n\
             source: &Instance,\n\
             inputs: &[NamedInput<'_>],\n\
         ) -> Result<Instance, RuntimeError> {\n\
             Ok(execute_outputs_with_sources(source, inputs)?.primary)\n\
         }\n\n\
         pub fn execute_with_sources_and_context(\n\
             source: &Instance,\n\
             inputs: &[NamedInput<'_>],\n\
             execution: &ExecutionContext<'_>,\n\
         ) -> Result<Instance, RuntimeError> {\n\
             Ok(execute_outputs_with_sources_and_context(source, inputs, execution)?.primary)\n\
         }\n\n\
         pub fn execute_outputs(source: &Instance) -> Result<ExecutionOutputs, RuntimeError> {\n\
             execute_outputs_with_sources(source, &[])\n\
         }\n\n\
         pub fn execute_outputs_with_context(\n\
             source: &Instance,\n\
             execution: &ExecutionContext<'_>,\n\
         ) -> Result<ExecutionOutputs, RuntimeError> {\n\
             execute_outputs_with_sources_and_context(source, &[], execution)\n\
         }\n\n\
         pub fn execute_outputs_with_sources(\n\
             source: &Instance,\n\
             inputs: &[NamedInput<'_>],\n\
         ) -> Result<ExecutionOutputs, RuntimeError> {\n\
             let inputs = validate_named_inputs(inputs)?;\n\
             execute_outputs_from_context(&ScopeContext::with_named_inputs(source, &inputs))\n\
         }\n\n\
         pub fn execute_outputs_with_sources_and_context(\n\
             source: &Instance,\n\
             inputs: &[NamedInput<'_>],\n\
             execution: &ExecutionContext<'_>,\n\
         ) -> Result<ExecutionOutputs, RuntimeError> {\n\
             let inputs = validate_named_inputs(inputs)?;\n\
             execute_outputs_from_context(&ScopeContext::with_named_inputs_and_execution_context(\n\
                 source,\n\
                 &inputs,\n\
                 execution,\n\
             ))\n\
         }\n\n",
    );

    let input_names = program
        .extra_sources
        .iter()
        .map(|input| rust_string(&input.name))
        .collect::<Vec<_>>()
        .join(", ");
    source.push_str(&format!(
        "pub const EXTRA_SOURCE_NAMES: &[&str] = &[{input_names}];\n\n"
    ));
    source.push_str(
        "fn validate_named_inputs<'a>(\n    inputs: &[NamedInput<'a>],\n) -> Result<Vec<NamedInput<'a>>, RuntimeError> {\n",
    );
    if program.extra_sources.is_empty() {
        source.push_str(
            "    if let Some(input) = inputs.first() {\n        return Err(RuntimeError::UnexpectedNamedSource {\n            name: input.name.to_string(),\n        });\n    }\n    Ok(Vec::new())\n}\n\n",
        );
    } else {
        source.push_str(&format!(
            "    let mut matched: Vec<Option<NamedInput<'a>>> = vec![None; {}];\n",
            program.extra_sources.len()
        ));
        source.push_str("    for input in inputs {\n        let index = match input.name {\n");
        for (index, input) in program.extra_sources.iter().enumerate() {
            source.push_str(&format!(
                "            {} => {index},\n",
                rust_string(&input.name)
            ));
        }
        source.push_str(
            "            _ => return Err(RuntimeError::UnexpectedNamedSource { name: input.name.to_string() }),\n        };\n        if matched[index].is_some() {\n            return Err(RuntimeError::DuplicateNamedSource {\n                name: EXTRA_SOURCE_NAMES[index],\n            });\n        }\n        matched[index] = Some(*input);\n    }\n    let mut ordered = Vec::with_capacity(EXTRA_SOURCE_NAMES.len());\n    for (index, name) in EXTRA_SOURCE_NAMES.iter().copied().enumerate() {\n        let Some(input) = matched[index].take() else {\n            return Err(RuntimeError::MissingNamedSource { name });\n        };\n        ordered.push(input);\n    }\n    Ok(ordered)\n}\n\n",
        );
    }

    source.push_str(
        "fn execute_outputs_from_context(\n    context: &ScopeContext<'_>,\n) -> Result<ExecutionOutputs, RuntimeError> {\n    evaluate_failure_rules(context)?;\n    let primary = scope_root(context)?;\n",
    );
    if program.extra_targets.is_empty() {
        source.push_str("    let extras = Vec::new();\n");
    } else {
        source.push_str(&format!(
            "    let mut extras = Vec::with_capacity({});\n",
            program.extra_targets.len()
        ));
        for (index, target) in program.extra_targets.iter().enumerate() {
            source.push_str(&format!(
                "    extras.push(NamedOutput {{\n        name: {},\n        instance: scope_extra_{index}(context)?,\n    }});\n",
                rust_string(&target.name)
            ));
        }
    }
    source.push_str("    Ok(ExecutionOutputs { primary, extras })\n}\n\n");

    let functions = program
        .user_functions
        .iter()
        .map(|function| (function.id, function))
        .collect::<BTreeMap<_, _>>();
    for function in &program.user_functions {
        source.push_str(&render_user_function(function, &functions)?);
    }
    for node in &program.expressions {
        source.push_str(&render_expression(
            node.id,
            &node.expression,
            "expression_",
            None,
            &functions,
        )?);
    }
    source.push_str(&failure::render(program));

    let mut scopes = Vec::new();
    collect_scopes(&program.root, "scope_root".to_string(), &mut scopes);
    for (index, target) in program.extra_targets.iter().enumerate() {
        collect_scopes(&target.root, format!("scope_extra_{index}"), &mut scopes);
    }
    for (name, scope, child_names, segment_names) in scopes {
        source.push_str(&render_scope(&name, scope, &child_names, &segment_names)?);
    }
    Ok(source)
}

fn render_user_function(
    function: &UserFunctionProgram,
    functions: &BTreeMap<FunctionId, &UserFunctionProgram>,
) -> Result<String, EmitError> {
    let prefix = format!("user_function_{}_expression_", function.id.get());
    let parameters = function
        .parameters
        .iter()
        .enumerate()
        .map(|(index, parameter)| (parameter.id, index))
        .collect::<BTreeMap<_, _>>();
    let mut output = String::new();
    for expression in &function.expressions {
        output.push_str(&render_expression(
            expression.id,
            &expression.expression,
            &prefix,
            Some(&parameters),
            functions,
        )?);
    }
    output.push_str(&format!(
        "fn user_function_{}(\n    context: &ScopeContext<'_>,\n    parameters: &[Value],\n) -> Result<Value, RuntimeError> {{\n    let output = {}{}(context, parameters)?;\n    adapt_user_function_value(output, ScalarType::{}, {}, None)\n}}\n\n",
        function.id.get(),
        prefix,
        function.output,
        scalar_type_name(function.output_type),
        function.id.get(),
    ));
    Ok(output)
}

fn render_expression(
    id: NodeId,
    expression: &Expression,
    prefix: &str,
    parameters: Option<&BTreeMap<FunctionParameterId, usize>>,
    functions: &BTreeMap<FunctionId, &UserFunctionProgram>,
) -> Result<String, EmitError> {
    let parameter_argument = parameters.map(|_| ", parameters").unwrap_or_default();
    let call_expression =
        |node: NodeId, context: &str| format!("{prefix}{node}({context}{parameter_argument})");
    let body = match expression {
        Expression::SourceField { frame, path } => {
            let path = path
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            match frame {
                Some(frame) => {
                    let frame = frame
                        .iter()
                        .map(|segment| rust_string(segment))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!(
                        "context.resolve_scalar_in_frame(&[{frame}], &[{path}]).map_err(RuntimeError::from)"
                    )
                }
                None => {
                    format!("context.resolve_scalar(&[{path}]).map_err(RuntimeError::from)")
                }
            }
        }
        Expression::XmlSerialize {
            frame,
            path,
            schema,
            declaration,
            indent,
            namespace,
        } => {
            let schema = serde_json::to_string(schema)
                .map_err(|error| EmitError::SchemaSerialization(error.to_string()))?;
            let path = render_string_path(path);
            let frame = frame.as_ref().map_or_else(
                || "None".to_string(),
                |frame| format!("Some(&[{}][..])", render_string_path(frame)),
            );
            let namespace = namespace.as_ref().map_or_else(
                || "None".to_string(),
                |namespace| format!("Some({})", rust_string(namespace)),
            );
            format!(
                "{{\n        let instance = context.resolve_xml_instance({frame}, &[{path}])?;\n        serialize_xml({id}, {}, instance, {declaration}, {indent}, {namespace})\n    }}",
                rust_string(&schema)
            )
        }
        Expression::XmlMixedContent {
            frame,
            path,
            replacements,
        } => {
            let path = render_string_path(path);
            let frame = frame.as_ref().map_or_else(
                || "None".to_string(),
                |frame| format!("Some(&[{}][..])", render_string_path(frame)),
            );
            let replacements = replacements
                .iter()
                .map(|replacement| {
                    format!(
                        "XmlMixedContentReplacement {{ element: {}, collection: &[{}], expression: {prefix}{} }}",
                        rust_string(&replacement.element),
                        render_string_path(&replacement.collection),
                        replacement.expression,
                    )
                })
                .collect::<Vec<_>>()
                .join(",\n            ");
            format!(
                "xml_mixed_content(\n        context,\n        {frame},\n        &[{path}],\n        &[\n            {replacements}\n        ],\n    )"
            )
        }
        Expression::SourceDocumentPath => {
            "context.source_document_path().map_err(RuntimeError::from)".into()
        }
        Expression::Position { collection } => {
            let collection = collection
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            format!("Ok(Value::Int(context.position(&[{collection}]) as i64))")
        }
        Expression::JoinField {
            join,
            collection,
            path,
        } => {
            let collection = render_string_path(collection);
            let path = render_string_path(path);
            format!(
                "context.resolve_join_scalar({}, &[{collection}], &[{path}]).map_err(RuntimeError::from)",
                join.get()
            )
        }
        Expression::JoinPosition { join } => format!(
            "Ok(Value::Int(context.join_position({})? as i64))",
            join.get()
        ),
        Expression::Const { value } => {
            format!("Ok({})", rust_value(id, value)?)
        }
        Expression::FunctionParameter { parameter } => {
            let index = parameters
                .and_then(|parameters| parameters.get(parameter))
                .copied()
                .ok_or(ProgramValidationError::FunctionParameterInMain {
                    node: id,
                    parameter: *parameter,
                })?;
            format!("Ok(parameters[{index}].clone())")
        }
        Expression::RuntimeValue { value } => format!(
            "context.runtime_value(RuntimeValue::{})",
            runtime_value_name(*value)
        ),
        Expression::Call { function, args } => {
            let mut body = String::from("{\n        let args = vec![\n");
            for arg in args {
                body.push_str(&format!(
                    "            {}?,\n",
                    call_expression(*arg, "context")
                ));
            }
            body.push_str(&format!(
                "        ];\n        call({}, &args)\n    }}",
                rust_string(function.as_str())
            ));
            body
        }
        Expression::UserFunctionCall { function, args } => {
            let definition = functions.get(function).ok_or({
                ProgramValidationError::MissingUserFunction {
                    owner: None,
                    node: id,
                    function: *function,
                }
            })?;
            let mut body = String::from("{\n");
            for (index, (argument, parameter)) in
                args.iter().zip(&definition.parameters).enumerate()
            {
                body.push_str(&format!(
                    "        let argument_{index} = adapt_user_function_value(\n            {}?,\n            ScalarType::{},\n            {},\n            Some({}),\n        )?;\n",
                    call_expression(*argument, "context"),
                    scalar_type_name(parameter.ty),
                    function.get(),
                    parameter.id.get(),
                ));
            }
            let arguments = (0..args.len())
                .map(|index| format!("argument_{index}"))
                .collect::<Vec<_>>()
                .join(", ");
            body.push_str(&format!(
                "        user_function_{}(context, &[{arguments}])\n    }}",
                function.get()
            ));
            body
        }
        Expression::If {
            condition,
            then,
            else_,
        } => {
            let condition_call = call_expression(*condition, "context");
            let then_call = call_expression(*then, "context");
            let else_call = call_expression(*else_, "context");
            format!(
                "{{\n        let condition = {condition_call}?;\n        if require_bool({condition}, condition)? {{\n            {then_call}\n        }} else {{\n            {else_call}\n        }}\n    }}"
            )
        }
        Expression::ValueMap {
            input,
            input_type,
            table,
            default,
        } => {
            let input_type = input_type.map_or_else(
                || "None".to_string(),
                |value| format!("Some(ScalarType::{})", scalar_type_name(value)),
            );
            let table = table
                .iter()
                .map(|(from, to)| {
                    Ok(format!(
                        "({}, {})",
                        rust_value(id, from)?,
                        rust_value(id, to)?
                    ))
                })
                .collect::<Result<Vec<_>, EmitError>>()?
                .join(", ");
            let default = match default {
                Some(value) => format!("Some({})", rust_value(id, value)?),
                None => "None".to_string(),
            };
            let input = call_expression(*input, "context");
            format!(
                "{{\n        let input = {input}?;\n        Ok(value_map(input, {input_type}, &[{table}], {default}))\n    }}"
            )
        }
        Expression::Lookup {
            collection,
            key,
            matches,
            value,
        } => {
            let collection = render_string_path(collection);
            let key = render_string_path(key);
            let value = render_string_path(value);
            format!(
                "{{\n        let needle = expression_{matches}(context)?;\n        context.lookup(&[{collection}], &[{key}], &needle, &[{value}]).map_err(RuntimeError::from)\n    }}"
            )
        }
        Expression::CollectionFind {
            collection,
            predicate,
            value,
        } => {
            let collection = render_string_path(collection);
            format!(
                "{{\n        let candidates = context.collection_find_items(&[{collection}])?;\n        for item_context in candidates {{\n            let predicate = expression_{predicate}(&item_context)?;\n            if collection_find_selected({predicate}, predicate)? {{\n                return expression_{value}(&item_context);\n            }}\n        }}\n        Ok(Value::Null)\n    }}"
            )
        }
        Expression::Aggregate {
            function,
            collection,
            value,
            arg,
        } => {
            let collection = collection
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            let mut body = format!(
                "{{\n        let item_contexts = context.aggregate_items(&[{collection}]);\n        let mut values = Vec::with_capacity(item_contexts.len());\n        for item_context in item_contexts {{\n"
            );
            match value {
                AggregateValue::Path(path) => {
                    let path = path
                        .iter()
                        .map(|segment| rust_string(segment))
                        .collect::<Vec<_>>()
                        .join(", ");
                    body.push_str(&format!(
                        "            values.push(item_context.aggregate_current_scalar(&[{path}]));\n"
                    ));
                }
                AggregateValue::Expression(expression) => body.push_str(&format!(
                    "            values.push(expression_{expression}(&item_context)?);\n"
                )),
            }
            body.push_str("        }\n");
            match arg {
                Some(arg) => body.push_str(&format!(
                    "        let arg = Some(expression_{arg}(context)?);\n"
                )),
                None => body.push_str("        let arg = None;\n"),
            }
            body.push_str(&format!(
                "        aggregate(AggregateFunction::{}, &values, arg)\n    }}",
                aggregate_function_name(*function)
            ));
            body
        }
        Expression::JoinAggregate {
            function,
            join,
            expression,
            arg,
        } => {
            let tuples = render_inner_join_call(join).unwrap_or_else(|| "Vec::new()".into());
            let mut body = format!("{{\n        let tuple_contexts = {tuples};\n");
            match expression {
                Some(expression) => body.push_str(&format!(
                    "        let mut values = Vec::with_capacity(tuple_contexts.len());\n        for tuple_context in tuple_contexts {{\n            values.push(expression_{expression}(&tuple_context)?);\n        }}\n"
                )),
                None => body.push_str(
                    "        let values = vec![Value::Null; tuple_contexts.len()];\n",
                ),
            }
            match arg {
                Some(arg) => body.push_str(&format!(
                    "        let arg = Some(expression_{arg}(context)?);\n"
                )),
                None => body.push_str("        let arg = None;\n"),
            }
            body.push_str(&format!(
                "        aggregate(AggregateFunction::{}, &values, arg)\n    }}",
                aggregate_function_name(*function)
            ));
            body
        }
        Expression::SequenceExists {
            sequence,
            predicate,
        } => {
            let mut body = String::from("{\n");
            render_generated_values(sequence, "        ", &mut body);
            body.push_str(&format!(
                "        let generated_items = GeneratedItems::new(sequence_values);\n        for item_context in context.generated_item_contexts(&generated_items) {{\n            let predicate = expression_{predicate}(&item_context)?;\n            if require_bool({predicate}, predicate)? {{\n                return Ok(Value::Bool(true));\n            }}\n        }}\n        Ok(Value::Bool(false))\n    }}"
            ));
            body
        }
        Expression::SequenceItemAt { sequence, index } => {
            let mut body = String::from("{\n");
            render_generated_values(sequence, "        ", &mut body);
            body.push_str(&format!(
                "        let index = expression_{index}(context)?;\n        aggregate(AggregateFunction::ItemAt, &sequence_values, Some(index))\n    }}"
            ));
            body
        }
    };
    let parameters_argument = parameters
        .map(|_| ", parameters: &[Value]")
        .unwrap_or_default();
    Ok(format!(
        "fn {prefix}{id}(context: &ScopeContext<'_>{parameters_argument}) -> Result<Value, RuntimeError> {{\n    let _ = context;\n    {body}\n}}\n\n"
    ))
}

fn render_string_path(path: &[String]) -> String {
    path.iter()
        .map(|segment| rust_string(segment))
        .collect::<Vec<_>>()
        .join(", ")
}

const fn aggregate_function_name(function: AggregateFunction) -> &'static str {
    match function {
        AggregateFunction::Count => "Count",
        AggregateFunction::Sum => "Sum",
        AggregateFunction::Avg => "Avg",
        AggregateFunction::Min => "Min",
        AggregateFunction::Max => "Max",
        AggregateFunction::Join => "Join",
        AggregateFunction::ItemAt => "ItemAt",
    }
}

const fn runtime_value_name(value: RuntimeValue) -> &'static str {
    match value {
        RuntimeValue::MappingFilePath => "MappingFilePath",
        RuntimeValue::MainMappingFilePath => "MainMappingFilePath",
        RuntimeValue::CurrentDateTime => "CurrentDateTime",
    }
}

fn collect_scopes<'a>(
    scope: &'a TargetScope,
    name: String,
    output: &mut Vec<(String, &'a TargetScope, Vec<String>, Vec<String>)>,
) {
    let child_names = scope
        .children
        .iter()
        .enumerate()
        .map(|(index, _)| format!("{name}_{index}"))
        .collect::<Vec<_>>();
    let segment_names = scope
        .iteration
        .as_ref()
        .and_then(IterationPlan::concatenated)
        .map(|sequence| {
            sequence
                .iter()
                .enumerate()
                .map(|(index, _)| format!("{name}_segment_{index}"))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();
    output.push((name, scope, child_names.clone(), segment_names.clone()));
    if let Some(sequence) = scope
        .iteration
        .as_ref()
        .and_then(IterationPlan::concatenated)
    {
        for (segment, segment_name) in sequence.iter().zip(segment_names) {
            collect_scopes(segment, segment_name, output);
        }
    }
    for (child, child_name) in scope.children.iter().zip(child_names) {
        collect_scopes(child, child_name, output);
    }
}

fn render_scope(
    name: &str,
    scope: &TargetScope,
    child_names: &[String],
    segment_names: &[String],
) -> Result<String, EmitError> {
    let mut output =
        format!("fn {name}(context: &ScopeContext<'_>) -> Result<Instance, RuntimeError> {{\n");
    if let Some(iteration) = &scope.iteration {
        if iteration.concatenated().is_some() {
            output.push_str(&render_concatenated_scope(iteration, segment_names));
        } else {
            output.push_str(&render_iteration_scope(scope, iteration, child_names));
        }
    } else {
        output.push_str(&render_scope_item(scope, child_names, "    ", "context"));
        if scope.repeating {
            output.push_str("    Ok(repeated([output]))\n");
        } else {
            output.push_str("    Ok(output)\n");
        }
    }
    output.push_str("}\n\n");
    Ok(output)
}

fn render_concatenated_scope(iteration: &IterationPlan, segment_names: &[String]) -> String {
    let mut output = String::from("    let mut outputs = Vec::new();\n");
    let variant = match iteration.output() {
        IterationOutput::Repeated => "Repeated",
        IterationOutput::MappedSequence => "MappedSequence",
        IterationOutput::First => unreachable!("validated scope sequences cannot use First"),
    };
    for (index, segment_name) in segment_names.iter().enumerate() {
        output.push_str(&format!(
            "    let segment_{index} = {segment_name}(context)?;\n    let Instance::{variant}(segment_{index}) = segment_{index} else {{\n        unreachable!(\"validated scope sequence segment output\");\n    }};\n    outputs.extend(segment_{index});\n"
        ));
    }
    match iteration.output() {
        IterationOutput::Repeated => output.push_str("    Ok(repeated(outputs))\n"),
        IterationOutput::MappedSequence => {
            output.push_str("    Ok(Instance::MappedSequence(outputs))\n");
        }
        IterationOutput::First => unreachable!("validated scope sequences cannot use First"),
    }
    output
}

fn render_iteration_scope(
    scope: &TargetScope,
    iteration: &IterationPlan,
    child_names: &[String],
) -> String {
    let mut output = String::new();
    let sort = iteration.sort();
    let filter_before_sort = iteration.filter().is_some()
        && sort.is_some_and(|sort| sort.filter_order() == SortFilterOrder::FilterThenSort);
    let has_windows =
        !iteration.windows().is_empty() || iteration.output() == IterationOutput::First;
    let has_grouping = iteration.grouping().is_some();
    let renumber_output =
        iteration.filter().is_some() || sort.is_some() || has_grouping || has_windows;

    let candidates_are_reassigned =
        sort.is_some() || has_windows || has_grouping && iteration.filter().is_some();
    render_iteration_candidates(iteration.input(), candidates_are_reassigned, &mut output);
    if filter_before_sort {
        render_prefilter(iteration.filter(), &mut output);
    }
    if let Some(sort) = sort {
        let keys = sort.keys().collect::<Vec<_>>();
        output.push_str("    let mut keyed_candidates = Vec::with_capacity(candidates.len());\n");
        output.push_str("    for candidate in candidates {\n        let keys = [\n");
        for key in &keys {
            output.push_str(&format!(
                "            expression_{}(&candidate)?,\n",
                key.expression
            ));
        }
        output.push_str("        ];\n        keyed_candidates.push((candidate, keys));\n    }\n");
        output.push_str("    candidates = sort_candidates(keyed_candidates, [\n");
        for key in &keys {
            let direction = if key.descending {
                "Descending"
            } else {
                "Ascending"
            };
            output.push_str(&format!("        SortDirection::{direction},\n"));
        }
        output.push_str(
            "    ]);\n    candidates = candidates\n        .into_iter()\n        .enumerate()\n        .map(|(index, candidate)| candidate.with_compact_last_position(index + 1))\n        .collect();\n",
        );
    }

    render_windows(iteration, &mut output);
    if (has_windows || has_grouping) && !filter_before_sort {
        render_prefilter(iteration.filter(), &mut output);
    }
    if let Some(grouping) = iteration.grouping() {
        render_grouping(
            iteration.input(),
            grouping,
            iteration.post_group_filter(),
            has_windows,
            &mut output,
        );
    }
    if has_windows {
        output.push_str("    candidates = apply_sequence_windows(candidates, &windows);\n");
    }

    output.push_str("    let mut outputs = Vec::with_capacity(candidates.len());\n");
    output.push_str("    for item_context in candidates {\n");
    if !filter_before_sort
        && !has_windows
        && !has_grouping
        && let Some(filter) = iteration.filter()
    {
        output.push_str(&format!(
            "        let filter_value = expression_{filter}(&item_context)?;\n        if !require_bool({filter}, filter_value)? {{\n            continue;\n        }}\n"
        ));
    }
    let item_context = if renumber_output {
        output.push_str(
            "        let output_context = item_context.with_compact_last_position(outputs.len() + 1);\n",
        );
        "&output_context"
    } else {
        "&item_context"
    };
    output.push_str(&render_scope_item(
        scope,
        child_names,
        "        ",
        item_context,
    ));
    output.push_str("        outputs.push(output);\n    }\n");
    match iteration.output() {
        IterationOutput::Repeated => output.push_str("    Ok(repeated(outputs))\n"),
        IterationOutput::MappedSequence => {
            output.push_str("    Ok(Instance::MappedSequence(outputs))\n");
        }
        IterationOutput::First => output
            .push_str("    Ok(outputs.into_iter().next().unwrap_or_else(|| group(Vec::new())))\n"),
    }
    output
}

fn render_grouping(
    input: &IterationSource,
    grouping: GroupingPlan,
    post_group_filter: Option<NodeId>,
    candidates_are_reassigned: bool,
    output: &mut String,
) {
    let wrapper = match input {
        IterationSource::Source(source) => source.path().last().map_or_else(
            || "None".to_string(),
            |name| format!("Some({})", rust_string(name)),
        ),
        IterationSource::Generated(_)
        | IterationSource::InnerJoin(_)
        | IterationSource::Concatenate(_) => "None".to_string(),
    };
    let binding = if candidates_are_reassigned {
        "let mut candidates"
    } else {
        "let candidates"
    };
    match grouping {
        GroupingPlan::By { key } => {
            output.push_str(&format!(
                "    let mut grouping_candidates = Vec::with_capacity(candidates.len());\n    for candidate in candidates {{\n        let key = expression_{key}(&candidate)?;\n"
            ));
            render_post_group_filter(post_group_filter, output);
            let tuple = if post_group_filter.is_some() {
                "(candidate, key, retained)"
            } else {
                "(candidate, key)"
            };
            let function = if post_group_filter.is_some() {
                "by_where_any"
            } else {
                "by"
            };
            output.push_str(&format!(
                "        grouping_candidates.push({tuple});\n    }}\n    let grouped_items = GroupedItems::{function}(grouping_candidates, {wrapper});\n    {binding} = grouped_items.contexts();\n"
            ));
        }
        GroupingPlan::AdjacentBy { key } => {
            output.push_str(&format!(
                "    let mut grouping_candidates = Vec::with_capacity(candidates.len());\n    for candidate in candidates {{\n        let key = expression_{key}(&candidate)?;\n"
            ));
            render_post_group_filter(post_group_filter, output);
            let tuple = if post_group_filter.is_some() {
                "(candidate, key, retained)"
            } else {
                "(candidate, key)"
            };
            let function = if post_group_filter.is_some() {
                "adjacent_by_where_any"
            } else {
                "adjacent_by"
            };
            output.push_str(&format!(
                "        grouping_candidates.push({tuple});\n    }}\n    let grouped_items = GroupedItems::{function}(grouping_candidates, {wrapper});\n    {binding} = grouped_items.contexts();\n"
            ));
        }
        GroupingPlan::StartingWith { predicate } => {
            output.push_str(&format!(
                "    let mut grouping_candidates = Vec::with_capacity(candidates.len());\n    for candidate in candidates {{\n        let starts = expression_{predicate}(&candidate)?;\n        let starts = require_bool({predicate}, starts)?;\n"
            ));
            render_post_group_filter(post_group_filter, output);
            let tuple = if post_group_filter.is_some() {
                "(candidate, starts, retained)"
            } else {
                "(candidate, starts)"
            };
            let function = if post_group_filter.is_some() {
                "starting_with_where_any"
            } else {
                "starting_with"
            };
            output.push_str(&format!(
                "        grouping_candidates.push({tuple});\n    }}\n    let grouped_items = GroupedItems::{function}(grouping_candidates, {wrapper});\n    {binding} = grouped_items.contexts();\n"
            ));
        }
        GroupingPlan::EndingWith { predicate } => {
            output.push_str(&format!(
                "    let mut grouping_candidates = Vec::with_capacity(candidates.len());\n    for candidate in candidates {{\n        let ends = expression_{predicate}(&candidate)?;\n        let ends = require_bool({predicate}, ends)?;\n"
            ));
            render_post_group_filter(post_group_filter, output);
            let tuple = if post_group_filter.is_some() {
                "(candidate, ends, retained)"
            } else {
                "(candidate, ends)"
            };
            let function = if post_group_filter.is_some() {
                "ending_with_where_any"
            } else {
                "ending_with"
            };
            output.push_str(&format!(
                "        grouping_candidates.push({tuple});\n    }}\n    let grouped_items = GroupedItems::{function}(grouping_candidates, {wrapper});\n    {binding} = grouped_items.contexts();\n"
            ));
        }
        GroupingPlan::IntoBlocks { size } => {
            output.push_str(&format!(
                "    let group_size = item_count({size}, expression_{size}(context)?)?;\n"
            ));
            let function = if post_group_filter.is_some() {
                output.push_str(
                    "    let mut grouping_candidates = Vec::with_capacity(candidates.len());\n    for candidate in candidates {\n",
                );
                render_post_group_filter(post_group_filter, output);
                output
                    .push_str("        grouping_candidates.push((candidate, retained));\n    }\n");
                "into_blocks_where_any"
            } else {
                output.push_str("    let grouping_candidates = candidates;\n");
                "into_blocks"
            };
            output.push_str(&format!(
                "    let grouped_items = GroupedItems::{function}(grouping_candidates, {wrapper}, group_size, {size})?;\n    {binding} = grouped_items.contexts();\n"
            ));
        }
    }
}

fn render_post_group_filter(post_group_filter: Option<NodeId>, output: &mut String) {
    if let Some(predicate) = post_group_filter {
        output.push_str(&format!(
            "        let retained = expression_{predicate}(&candidate)?;\n        let retained = require_bool({predicate}, retained)?;\n"
        ));
    }
}

fn render_iteration_candidates(
    input: &IterationSource,
    candidates_are_reassigned: bool,
    output: &mut String,
) {
    let binding = if candidates_are_reassigned {
        "let mut candidates"
    } else {
        "let candidates"
    };
    match input {
        IterationSource::Source(source) => {
            let path = source
                .path()
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!(
                "    {binding} = context.walk_source(&[{path}]);\n"
            ));
        }
        IterationSource::Generated(sequence) => {
            render_generated_values(sequence, "    ", output);
            output.push_str(
                &format!(
                    "    let generated_items = GeneratedItems::new(sequence_values);\n    {binding} = context.generated_items(&generated_items);\n"
                ),
            );
        }
        IterationSource::InnerJoin(join) => render_inner_join(join, binding, output),
        IterationSource::Concatenate(_) => {
            unreachable!("concatenated scopes render before candidate iteration")
        }
    }
}

fn render_inner_join(join: &InnerJoin, binding: &str, output: &mut String) {
    let Some(call) = render_inner_join_call(join) else {
        output.push_str(&format!("    {binding} = Vec::new();\n"));
        return;
    };
    output.push_str(&format!("    {binding} = {call};\n"));
}

fn render_inner_join_call(join: &InnerJoin) -> Option<String> {
    let mut sources = join.plan().sources();
    let first = sources.next()?;
    let mut stages = join.plan().stages();
    let (second_source, second_conditions) = stages.next()?;
    let first = render_string_path(first.collection());
    let second = render_inner_join_stage(second_source, second_conditions);
    let rest = stages
        .map(|(source, conditions)| render_inner_join_stage(source, conditions))
        .collect::<Vec<_>>()
        .join(", ");
    Some(format!(
        "context.inner_join({}, &[{first}], {second}, &[{rest}])?",
        join.id().get()
    ))
}

fn render_inner_join_stage(
    source: &codegen::JoinSource,
    conditions: &codegen::JoinConditions,
) -> String {
    let collection = render_string_path(source.collection());
    let keys = conditions
        .iter()
        .map(|key| {
            let left_collection = render_string_path(key.left_collection());
            let left_path = render_string_path(key.left_path());
            let right_path = render_string_path(key.right_path());
            format!(
                "InnerJoinKey {{ left_collection: &[{left_collection}], left_path: &[{left_path}], right_path: &[{right_path}] }}"
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("InnerJoinStage {{ collection: &[{collection}], keys: &[{keys}] }}")
}

fn render_generated_values(sequence: &GeneratedSequence, indent: &str, output: &mut String) {
    match sequence {
        GeneratedSequence::Tokenize {
            input, delimiter, ..
        } => output.push_str(&format!(
            "{indent}let sequence_input = expression_{input}(context)?;\n{indent}let sequence_values = if sequence_input == Value::Null || sequence_input.is_json_null() {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_parameter = expression_{delimiter}(context)?;\n{indent}    if sequence_parameter == Value::Null || sequence_parameter.is_json_null() {{\n{indent}        Vec::new()\n{indent}    }} else {{\n{indent}        tokenize(sequence_input, sequence_parameter)?\n{indent}    }}\n{indent}}};\n"
        )),
        GeneratedSequence::TokenizeByLength { input, length, .. } => output.push_str(&format!(
            "{indent}let sequence_input = expression_{input}(context)?;\n{indent}let sequence_values = if sequence_input == Value::Null || sequence_input.is_json_null() {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_parameter = expression_{length}(context)?;\n{indent}    if sequence_parameter == Value::Null || sequence_parameter.is_json_null() {{\n{indent}        Vec::new()\n{indent}    }} else {{\n{indent}        tokenize_by_length(sequence_input, sequence_parameter)?\n{indent}    }}\n{indent}}};\n"
        )),
        GeneratedSequence::TokenizeRegex {
            input,
            pattern,
            flags,
            ..
        } => {
            output.push_str(&format!(
                "{indent}let sequence_input = expression_{input}(context)?;\n{indent}let sequence_values = if sequence_input == Value::Null || sequence_input.is_json_null() {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_pattern = expression_{pattern}(context)?;\n{indent}    if sequence_pattern == Value::Null || sequence_pattern.is_json_null() {{\n{indent}        Vec::new()\n{indent}    }} else {{\n"
            ));
            match flags {
                Some(flags) => output.push_str(&format!(
                    "{indent}        let sequence_flags = expression_{flags}(context)?;\n{indent}        if sequence_flags == Value::Null || sequence_flags.is_json_null() {{\n{indent}            Vec::new()\n{indent}        }} else {{\n{indent}            tokenize_regex(sequence_input, sequence_pattern, Some(sequence_flags))?\n{indent}        }}\n"
                )),
                None => output.push_str(&format!(
                    "{indent}        tokenize_regex(sequence_input, sequence_pattern, None)?\n"
                )),
            }
            output.push_str(&format!("{indent}    }}\n{indent}}};\n"));
        }
        GeneratedSequence::RecursiveCollect {
            collection,
            children,
            descent_value,
            values,
            value,
            prefix,
            separator,
            ..
        } => {
            let path = |segments: &[String]| {
                segments
                    .iter()
                    .map(|segment| rust_string(segment))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let collection = path(collection);
            let children = path(children);
            let descent_value = path(descent_value);
            let values = path(values);
            let value = path(value);
            output.push_str(&format!(
                "{indent}let sequence_prefix = recursive_sequence_parameter(expression_{prefix}(context)?)?;\n{indent}let sequence_separator = recursive_sequence_parameter(expression_{separator}(context)?)?;\n{indent}let sequence_values = recursive_collect(\n{indent}    context,\n{indent}    RecursiveCollectPaths {{\n{indent}        collection: &[{collection}],\n{indent}        children: &[{children}],\n{indent}        descent_value: &[{descent_value}],\n{indent}        values: &[{values}],\n{indent}        value: &[{value}],\n{indent}    }},\n{indent}    &sequence_prefix,\n{indent}    &sequence_separator,\n{indent})?;\n"
            ));
        }
        GeneratedSequence::Range {
            from: Some(from),
            to,
            ..
        } => output.push_str(&format!(
            "{indent}let sequence_from = expression_{from}(context)?;\n{indent}let sequence_values = if sequence_from == Value::Null || sequence_from.is_json_null() {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    let sequence_to = expression_{to}(context)?;\n{indent}    if sequence_to == Value::Null || sequence_to.is_json_null() {{\n{indent}        Vec::new()\n{indent}    }} else {{\n{indent}        generate_sequence(Some(sequence_from), sequence_to)?\n{indent}    }}\n{indent}}};\n"
        )),
        GeneratedSequence::Range { from: None, to, .. } => output.push_str(&format!(
            "{indent}let sequence_to = expression_{to}(context)?;\n{indent}let sequence_values = if sequence_to == Value::Null || sequence_to.is_json_null() {{\n{indent}    Vec::new()\n{indent}}} else {{\n{indent}    generate_sequence(None, sequence_to)?\n{indent}}};\n"
        )),
    }
}

fn render_prefilter(filter: Option<NodeId>, output: &mut String) {
    let Some(filter) = filter else {
        return;
    };
    output.push_str(&format!(
        "    let mut filtered = Vec::with_capacity(candidates.len());\n    for candidate in candidates {{\n        let filter_value = expression_{filter}(&candidate)?;\n        if require_bool({filter}, filter_value)? {{\n            filtered.push(candidate);\n        }}\n    }}\n    candidates = filtered;\n"
    ));
}

fn render_windows(iteration: &IterationPlan, output: &mut String) {
    let has_windows =
        !iteration.windows().is_empty() || iteration.output() == IterationOutput::First;
    if !has_windows {
        return;
    }
    output.push_str(&format!(
        "    let mut windows = Vec::with_capacity({});\n",
        iteration.windows().len() + usize::from(iteration.output() == IterationOutput::First)
    ));
    for (index, window) in iteration.windows().iter().enumerate() {
        match *window {
            SequenceWindow::SkipFirst { count } => {
                render_single_window(index, "count", count, "SkipFirst", output)
            }
            SequenceWindow::First { count } => {
                render_single_window(index, "count", count, "First", output)
            }
            SequenceWindow::From { position } => {
                render_single_window(index, "position", position, "From", output)
            }
            SequenceWindow::Last { count } => {
                render_single_window(index, "count", count, "Last", output)
            }
            SequenceWindow::FromTo { first, last } => {
                output.push_str(&format!(
                    "    let window_{index}_first = item_count({first}, expression_{first}(context)?)?;\n    let window_{index}_last = item_count({last}, expression_{last}(context)?)?;\n    windows.push(SequenceWindow::FromTo {{ first: window_{index}_first, last: window_{index}_last }});\n"
                ));
            }
        }
    }
    if iteration.output() == IterationOutput::First {
        output.push_str("    windows.push(SequenceWindow::First(1));\n");
    }
}

fn render_single_window(
    index: usize,
    label: &str,
    expression: u32,
    kind: &str,
    output: &mut String,
) {
    output.push_str(&format!(
        "    let window_{index}_{label} = item_count({expression}, expression_{expression}(context)?)?;\n    windows.push(SequenceWindow::{kind}(window_{index}_{label}));\n"
    ));
}

fn render_scope_item(
    scope: &TargetScope,
    child_names: &[String],
    indent: &str,
    context: &str,
) -> String {
    let mut output = String::new();
    if let TargetConstruction::Scalar { expression } = scope.construction {
        output.push_str(&format!(
            "{indent}let output = scalar(expression_{expression}({context})?);\n"
        ));
        return output;
    }
    if matches!(scope.construction, TargetConstruction::CopyCurrentSource) {
        output.push_str(&format!(
            "{indent}let output = {context}.copy_current_group()?;\n"
        ));
        return output;
    }
    for (index, binding) in scope.bindings.iter().enumerate() {
        output.push_str(&format!(
            "{indent}let value_{index} = adapt_target_value(expression_{}({context})?, ScalarType::{});\n",
            binding.expression,
            scalar_type_name(binding.target_type)
        ));
    }

    let groups = binding_groups(&scope.bindings);
    for (group_index, group) in groups.iter().enumerate() {
        if !group.repeating {
            continue;
        }
        output.push_str(&format!(
            "{indent}let mut repeated_{group_index} = Vec::new();\n"
        ));
        for binding_index in &group.binding_indices {
            output.push_str(&format!(
                "{indent}if value_{binding_index} != Value::Null {{\n{indent}    repeated_{group_index}.push(scalar(value_{binding_index}));\n{indent}}}\n"
            ));
        }
    }

    let mut fields = Vec::new();
    for (group_index, binding_group) in groups.iter().enumerate() {
        let name = rust_string(&binding_group.target_field);
        if binding_group.repeating {
            fields.push(format!("field({name}, repeated(repeated_{group_index}))"));
        } else {
            let index = binding_group.binding_indices[0];
            fields.push(format!("field({name}, scalar(value_{index}))"));
        }
    }
    for (child, child_name) in scope.children.iter().zip(child_names) {
        fields.push(format!(
            "field({}, {child_name}({context})?)",
            rust_string(&child.target_field)
        ));
    }
    if fields.is_empty() {
        output.push_str(&format!("{indent}let output = group(Vec::new());\n"));
    } else {
        output.push_str(&format!("{indent}let output = group([\n"));
        for field in fields {
            output.push_str(&format!("{indent}    {field},\n"));
        }
        output.push_str(&format!("{indent}]);\n"));
    }
    output
}

struct BindingGroup {
    target_field: String,
    repeating: bool,
    binding_indices: Vec<usize>,
}

fn binding_groups(bindings: &[Binding]) -> Vec<BindingGroup> {
    let mut groups = Vec::<BindingGroup>::new();
    let mut indices = BTreeMap::<&str, usize>::new();
    for (binding_index, binding) in bindings.iter().enumerate() {
        if let Some(index) = indices.get(binding.target_field.as_str()).copied() {
            let group = &mut groups[index];
            group.binding_indices.push(binding_index);
        } else {
            indices.insert(&binding.target_field, groups.len());
            groups.push(BindingGroup {
                target_field: binding.target_field.clone(),
                repeating: binding.repeating,
                binding_indices: vec![binding_index],
            });
        }
    }
    groups
}

fn scalar_type_name(value: ScalarType) -> &'static str {
    match value {
        ScalarType::String => "String",
        ScalarType::Int => "Int",
        ScalarType::Float => "Float",
        ScalarType::Bool => "Bool",
    }
}

fn rust_value(_node: NodeId, value: &Value) -> Result<String, EmitError> {
    Ok(match value {
        Value::Null => "Value::Null".to_string(),
        Value::JsonNull(_) => "Value::json_null()".to_string(),
        Value::XmlNil(_) => "Value::xml_nil()".to_string(),
        Value::Bool(value) => format!("Value::Bool({value})"),
        Value::Int(i64::MIN) => "Value::Int(i64::MIN)".to_string(),
        Value::Int(value) => format!("Value::Int({value}_i64)"),
        Value::Float(value) => format!(
            "Value::Float(f64::from_bits(0x{:016x}_u64))",
            value.to_bits()
        ),
        Value::String(value) => format!("Value::String({}.to_string())", rust_string(value)),
    })
}

fn rust_string(value: &str) -> String {
    let escaped = value
        .chars()
        .flat_map(char::escape_default)
        .collect::<String>();
    format!("\"{escaped}\"")
}

fn toml_string(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\u{8}' => output.push_str("\\b"),
            '\t' => output.push_str("\\t"),
            '\n' => output.push_str("\\n"),
            '\u{c}' => output.push_str("\\f"),
            '\r' => output.push_str("\\r"),
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            character if character.is_ascii() && !character.is_control() => {
                output.push(character);
            }
            character if (character as u32) <= 0xffff => {
                output.push_str(&format!("\\u{:04X}", character as u32));
            }
            character => output.push_str(&format!("\\U{:08X}", character as u32)),
        }
    }
    output.push('"');
    output
}

#[cfg(test)]
mod tests;
