//! Deterministic Rust source generation for backend-neutral ferrule programs.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::fmt;

use codegen::{
    ArtifactPath, ArtifactPathError, ArtifactSet, ArtifactSetError, Binding, Expression,
    GeneratedFile, Program, ProgramValidationError, TargetScope, validate_program,
};
use ir::{ScalarType, Value};
use mapping::NodeId;

/// How a generated Cargo project locates ferrule's small Rust runtime.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RuntimeDependency {
    Path(String),
    Version(String),
    Git {
        repository: String,
        revision: String,
    },
}

/// Rust project generation settings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Options {
    pub package_name: String,
    pub runtime_dependency: RuntimeDependency,
}

/// Failure to render a complete Rust project.
#[derive(Debug)]
pub enum EmitError {
    InvalidProgram(ProgramValidationError),
    InvalidPackageName(String),
    NonFiniteFloat { node: NodeId },
    ArtifactPath(ArtifactPathError),
    ArtifactSet(ArtifactSetError),
}

impl fmt::Display for EmitError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidProgram(error) => error.fmt(formatter),
            Self::InvalidPackageName(name) => {
                write!(formatter, "invalid generated Rust package name {name:?}")
            }
            Self::NonFiniteFloat { node } => {
                write!(
                    formatter,
                    "graph node {node} contains a non-finite float literal"
                )
            }
            Self::ArtifactPath(error) => error.fmt(formatter),
            Self::ArtifactSet(error) => error.fmt(formatter),
        }
    }
}

impl std::error::Error for EmitError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::InvalidProgram(error) => Some(error),
            Self::ArtifactPath(error) => Some(error),
            Self::ArtifactSet(error) => Some(error),
            Self::InvalidPackageName(_) | Self::NonFiniteFloat { .. } => None,
        }
    }
}

impl From<ProgramValidationError> for EmitError {
    fn from(error: ProgramValidationError) -> Self {
        Self::InvalidProgram(error)
    }
}

impl From<ArtifactPathError> for EmitError {
    fn from(error: ArtifactPathError) -> Self {
        Self::ArtifactPath(error)
    }
}

impl From<ArtifactSetError> for EmitError {
    fn from(error: ArtifactSetError) -> Self {
        Self::ArtifactSet(error)
    }
}

/// Emits one buildable Rust library project.
pub fn emit(program: &Program, options: &Options) -> Result<ArtifactSet, EmitError> {
    validate_program(program)?;
    if !valid_package_name(&options.package_name) {
        return Err(EmitError::InvalidPackageName(options.package_name.clone()));
    }
    let manifest = render_manifest(options);
    let source = render_source(program)?;
    ArtifactSet::new([
        GeneratedFile::new(ArtifactPath::new("Cargo.toml")?, manifest),
        GeneratedFile::new(ArtifactPath::new("src/lib.rs")?, source),
    ])
    .map_err(EmitError::from)
}

fn valid_package_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
        && name
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphabetic())
}

fn render_manifest(options: &Options) -> String {
    let dependency = match &options.runtime_dependency {
        RuntimeDependency::Path(path) => format!("path = {}", toml_string(path)),
        RuntimeDependency::Version(version) => format!("version = {}", toml_string(version)),
        RuntimeDependency::Git {
            repository,
            revision,
        } => format!(
            "git = {}, rev = {}",
            toml_string(repository),
            toml_string(revision)
        ),
    };
    format!(
        "[package]\nname = {}\nversion = \"0.1.0\"\nedition = \"2024\"\npublish = false\n\n[dependencies]\ncodegen-runtime = {{ {dependency} }}\n",
        toml_string(&options.package_name)
    )
}

fn render_source(program: &Program) -> Result<String, EmitError> {
    let mut source = String::from(
        "// Generated by ferrule. Do not edit.\n\
         use codegen_runtime::{\n\
             Instance, RuntimeError, ScalarType, ScopeContext, Value, adapt_target_value, call,\n\
             field, group, repeated, require_bool, scalar,\n\
         };\n\n",
    );
    source.push_str(
        "pub fn execute(source: &Instance) -> Result<Instance, RuntimeError> {\n    scope_root(&ScopeContext::new(source))\n}\n\n",
    );

    for node in &program.expressions {
        source.push_str(&render_expression(node.id, &node.expression)?);
    }

    let mut scopes = Vec::new();
    collect_scopes(&program.root, "scope_root".to_string(), &mut scopes);
    for (name, scope, child_names) in scopes {
        source.push_str(&render_scope(&name, scope, &child_names)?);
    }
    Ok(source)
}

fn render_expression(id: NodeId, expression: &Expression) -> Result<String, EmitError> {
    let body = match expression {
        Expression::SourceField { path } => {
            let path = path
                .iter()
                .map(|segment| rust_string(segment))
                .collect::<Vec<_>>()
                .join(", ");
            format!("context.resolve_scalar(&[{path}]).map_err(RuntimeError::from)")
        }
        Expression::Const { value } => {
            format!("Ok({})", rust_value(id, value)?)
        }
        Expression::Call { function, args } => {
            let mut body = format!(
                "{{\n        let mut args = Vec::with_capacity({});\n",
                args.len()
            );
            for arg in args {
                body.push_str(&format!("        args.push(expression_{arg}(context)?);\n"));
            }
            body.push_str(&format!(
                "        call({}, &args)\n    }}",
                rust_string(function.as_str())
            ));
            body
        }
        Expression::If {
            condition,
            then,
            else_,
        } => format!(
            "{{\n        let condition = expression_{condition}(context)?;\n        if require_bool({condition}, condition)? {{\n            expression_{then}(context)\n        }} else {{\n            expression_{else_}(context)\n        }}\n    }}"
        ),
    };
    Ok(format!(
        "fn expression_{id}(context: &ScopeContext<'_>) -> Result<Value, RuntimeError> {{\n    let _ = context;\n    {body}\n}}\n\n"
    ))
}

fn collect_scopes<'a>(
    scope: &'a TargetScope,
    name: String,
    output: &mut Vec<(String, &'a TargetScope, Vec<String>)>,
) {
    let child_names = scope
        .children
        .iter()
        .enumerate()
        .map(|(index, _)| format!("{name}_{index}"))
        .collect::<Vec<_>>();
    output.push((name, scope, child_names.clone()));
    for (child, child_name) in scope.children.iter().zip(child_names) {
        collect_scopes(child, child_name, output);
    }
}

fn render_scope(
    name: &str,
    scope: &TargetScope,
    child_names: &[String],
) -> Result<String, EmitError> {
    let mut output =
        format!("fn {name}(context: &ScopeContext<'_>) -> Result<Instance, RuntimeError> {{\n");
    if let Some(iteration) = &scope.iteration {
        let path = iteration
            .path()
            .iter()
            .map(|segment| rust_string(segment))
            .collect::<Vec<_>>()
            .join(", ");
        output.push_str("    let mut outputs = Vec::new();\n");
        output.push_str(&format!(
            "    for item_context in context.walk_source(&[{path}]) {{\n"
        ));
        output.push_str(&render_scope_item(
            scope,
            child_names,
            "        ",
            "&item_context",
        ));
        output.push_str("        outputs.push(output);\n");
        output.push_str("    }\n");
        output.push_str("    Ok(repeated(outputs))\n");
    } else {
        output.push_str(&render_scope_item(scope, child_names, "    ", "context"));
        if scope.repeating {
            output.push_str("    Ok(repeated([output]))\n");
        } else {
            output.push_str("    Ok(output)\n");
        }
    }
    output.push_str("}\n\n");
    Ok(output)
}

fn render_scope_item(
    scope: &TargetScope,
    child_names: &[String],
    indent: &str,
    context: &str,
) -> String {
    let mut output = String::new();
    for (index, binding) in scope.bindings.iter().enumerate() {
        output.push_str(&format!(
            "{indent}let value_{index} = adapt_target_value(expression_{}({context})?, ScalarType::{});\n",
            binding.expression,
            scalar_type_name(binding.target_type)
        ));
    }

    let groups = binding_groups(&scope.bindings);
    for (group_index, group) in groups.iter().enumerate() {
        if !group.repeating {
            continue;
        }
        output.push_str(&format!(
            "{indent}let mut repeated_{group_index} = Vec::new();\n"
        ));
        for binding_index in &group.binding_indices {
            output.push_str(&format!(
                "{indent}if value_{binding_index} != Value::Null {{\n{indent}    repeated_{group_index}.push(scalar(value_{binding_index}));\n{indent}}}\n"
            ));
        }
    }

    let mut fields = Vec::new();
    for (group_index, binding_group) in groups.iter().enumerate() {
        let name = rust_string(&binding_group.target_field);
        if binding_group.repeating {
            fields.push(format!("field({name}, repeated(repeated_{group_index}))"));
        } else {
            let index = binding_group.binding_indices[0];
            fields.push(format!("field({name}, scalar(value_{index}))"));
        }
    }
    for (child, child_name) in scope.children.iter().zip(child_names) {
        fields.push(format!(
            "field({}, {child_name}({context})?)",
            rust_string(&child.target_field)
        ));
    }
    if fields.is_empty() {
        output.push_str(&format!("{indent}let output = group(Vec::new());\n"));
    } else {
        output.push_str(&format!("{indent}let output = group([\n"));
        for field in fields {
            output.push_str(&format!("{indent}    {field},\n"));
        }
        output.push_str(&format!("{indent}]);\n"));
    }
    output
}

struct BindingGroup {
    target_field: String,
    repeating: bool,
    binding_indices: Vec<usize>,
}

fn binding_groups(bindings: &[Binding]) -> Vec<BindingGroup> {
    let mut groups = Vec::<BindingGroup>::new();
    let mut indices = BTreeMap::<&str, usize>::new();
    for (binding_index, binding) in bindings.iter().enumerate() {
        if let Some(index) = indices.get(binding.target_field.as_str()).copied() {
            let group = &mut groups[index];
            group.binding_indices.push(binding_index);
        } else {
            indices.insert(&binding.target_field, groups.len());
            groups.push(BindingGroup {
                target_field: binding.target_field.clone(),
                repeating: binding.repeating,
                binding_indices: vec![binding_index],
            });
        }
    }
    groups
}

fn scalar_type_name(value: ScalarType) -> &'static str {
    match value {
        ScalarType::String => "String",
        ScalarType::Int => "Int",
        ScalarType::Float => "Float",
        ScalarType::Bool => "Bool",
    }
}

fn rust_value(node: NodeId, value: &Value) -> Result<String, EmitError> {
    Ok(match value {
        Value::Null => "Value::Null".to_string(),
        Value::XmlNil(_) => "Value::xml_nil()".to_string(),
        Value::Bool(value) => format!("Value::Bool({value})"),
        Value::Int(i64::MIN) => "Value::Int(i64::MIN)".to_string(),
        Value::Int(value) => format!("Value::Int({value}_i64)"),
        Value::Float(value) if value.is_finite() => {
            format!("Value::Float({value:?}_f64)")
        }
        Value::Float(_) => return Err(EmitError::NonFiniteFloat { node }),
        Value::String(value) => format!("Value::String({}.to_string())", rust_string(value)),
    })
}

fn rust_string(value: &str) -> String {
    let escaped = value
        .chars()
        .flat_map(char::escape_default)
        .collect::<String>();
    format!("\"{escaped}\"")
}

fn toml_string(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '\u{8}' => output.push_str("\\b"),
            '\t' => output.push_str("\\t"),
            '\n' => output.push_str("\\n"),
            '\u{c}' => output.push_str("\\f"),
            '\r' => output.push_str("\\r"),
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            character if character.is_ascii() && !character.is_control() => {
                output.push(character);
            }
            character if (character as u32) <= 0xffff => {
                output.push_str(&format!("\\u{:04X}", character as u32));
            }
            character => output.push_str(&format!("\\U{:08X}", character as u32)),
        }
    }
    output.push('"');
    output
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::process::Command;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;
    use codegen::{Binding, ExpressionNode, ScalarFunction, SourceIteration};
    use ir::SchemaNode;

    fn program() -> Program {
        Program {
            source: SchemaNode::group(
                "Source",
                vec![
                    SchemaNode::scalar("Name", ScalarType::String),
                    SchemaNode::scalar("First", ScalarType::Int),
                    SchemaNode::scalar("Second", ScalarType::Int),
                    SchemaNode::scalar("Condition", ScalarType::Bool),
                    SchemaNode::group(
                        "Parents",
                        vec![
                            SchemaNode::scalar("Id", ScalarType::Int),
                            SchemaNode::group(
                                "Children",
                                vec![SchemaNode::scalar("Name", ScalarType::String)],
                            )
                            .repeating(),
                        ],
                    )
                    .repeating(),
                ],
            ),
            target: SchemaNode::group(
                "Target",
                vec![
                    SchemaNode::scalar("Copied", ScalarType::String),
                    SchemaNode::scalar("Numbers", ScalarType::Int).repeating(),
                    SchemaNode::scalar("Sum", ScalarType::Int),
                    SchemaNode::scalar("Selected", ScalarType::Int),
                    SchemaNode::group(
                        "Nested",
                        vec![SchemaNode::scalar("Constant", ScalarType::String)],
                    )
                    .repeating(),
                    SchemaNode::group(
                        "Rows",
                        vec![
                            SchemaNode::scalar("ParentId", ScalarType::Int),
                            SchemaNode::scalar("ChildName", ScalarType::String),
                        ],
                    )
                    .repeating(),
                ],
            ),
            expressions: vec![
                ExpressionNode {
                    id: 1,
                    expression: Expression::SourceField {
                        path: vec!["Name".to_string()],
                    },
                },
                ExpressionNode {
                    id: 2,
                    expression: Expression::Const {
                        value: Value::Float(7.0),
                    },
                },
                ExpressionNode {
                    id: 3,
                    expression: Expression::Const { value: Value::Null },
                },
                ExpressionNode {
                    id: 4,
                    expression: Expression::Const {
                        value: Value::String("fixed".to_string()),
                    },
                },
                ExpressionNode {
                    id: 5,
                    expression: Expression::SourceField {
                        path: vec!["First".to_string()],
                    },
                },
                ExpressionNode {
                    id: 6,
                    expression: Expression::SourceField {
                        path: vec!["Second".to_string()],
                    },
                },
                ExpressionNode {
                    id: 7,
                    expression: Expression::Call {
                        function: ScalarFunction::Add,
                        args: vec![5, 6],
                    },
                },
                ExpressionNode {
                    id: 8,
                    expression: Expression::Const {
                        value: Value::Int(0),
                    },
                },
                ExpressionNode {
                    id: 9,
                    expression: Expression::Call {
                        function: ScalarFunction::Divide,
                        args: vec![5, 8],
                    },
                },
                ExpressionNode {
                    id: 10,
                    expression: Expression::SourceField {
                        path: vec!["Condition".to_string()],
                    },
                },
                ExpressionNode {
                    id: 11,
                    expression: Expression::If {
                        condition: 10,
                        then: 7,
                        else_: 9,
                    },
                },
                ExpressionNode {
                    id: 12,
                    expression: Expression::SourceField {
                        path: vec!["Parents".to_string(), "Id".to_string()],
                    },
                },
                ExpressionNode {
                    id: 13,
                    expression: Expression::SourceField {
                        path: vec![
                            "Parents".to_string(),
                            "Children".to_string(),
                            "Name".to_string(),
                        ],
                    },
                },
            ],
            root: TargetScope {
                target_field: String::new(),
                repeating: false,
                iteration: None,
                bindings: vec![
                    Binding {
                        target_field: "Copied".to_string(),
                        expression: 1,
                        target_type: ScalarType::String,
                        repeating: false,
                    },
                    Binding {
                        target_field: "Numbers".to_string(),
                        expression: 2,
                        target_type: ScalarType::Int,
                        repeating: true,
                    },
                    Binding {
                        target_field: "Numbers".to_string(),
                        expression: 3,
                        target_type: ScalarType::Int,
                        repeating: true,
                    },
                    Binding {
                        target_field: "Sum".to_string(),
                        expression: 7,
                        target_type: ScalarType::Int,
                        repeating: false,
                    },
                    Binding {
                        target_field: "Selected".to_string(),
                        expression: 11,
                        target_type: ScalarType::Int,
                        repeating: false,
                    },
                ],
                children: vec![
                    TargetScope {
                        target_field: "Nested".to_string(),
                        repeating: true,
                        iteration: None,
                        bindings: vec![Binding {
                            target_field: "Constant".to_string(),
                            expression: 4,
                            target_type: ScalarType::String,
                            repeating: false,
                        }],
                        children: Vec::new(),
                    },
                    TargetScope {
                        target_field: "Rows".to_string(),
                        repeating: true,
                        iteration: Some(SourceIteration::new(vec![
                            "Parents".to_string(),
                            "Children".to_string(),
                        ])),
                        bindings: vec![
                            Binding {
                                target_field: "ParentId".to_string(),
                                expression: 12,
                                target_type: ScalarType::Int,
                                repeating: false,
                            },
                            Binding {
                                target_field: "ChildName".to_string(),
                                expression: 13,
                                target_type: ScalarType::String,
                                repeating: false,
                            },
                        ],
                        children: Vec::new(),
                    },
                ],
            },
        }
    }

    #[test]
    fn emits_deterministic_rust_project() {
        let options = Options {
            package_name: "sample-map".to_string(),
            runtime_dependency: RuntimeDependency::Path("../runtime".to_string()),
        };
        let first = emit(&program(), &options).unwrap();
        let second = emit(&program(), &options).unwrap();
        assert_eq!(first, second);
        assert_eq!(
            first
                .files()
                .iter()
                .map(|file| file.path.as_str())
                .collect::<Vec<_>>(),
            ["Cargo.toml", "src/lib.rs"]
        );
        let source = first
            .files()
            .iter()
            .find(|file| file.path.as_str() == "src/lib.rs")
            .and_then(|file| std::str::from_utf8(&file.contents).ok())
            .unwrap();
        assert!(source.contains("adapt_target_value(expression_2(context)?, ScalarType::Int)"));
        assert!(source.contains("repeated_1.push(scalar(value_1))"));
        assert!(source.contains("scope_root_0(context)?"));
        assert!(
            source
                .contains("for item_context in context.walk_source(&[\"Parents\", \"Children\"])")
        );
        assert!(
            source.contains("adapt_target_value(expression_12(&item_context)?, ScalarType::Int)")
        );
    }

    #[test]
    fn rejects_invalid_package_names_and_non_finite_literals() {
        let options = Options {
            package_name: "not/a/package".to_string(),
            runtime_dependency: RuntimeDependency::Version("0.1.0".to_string()),
        };
        assert!(matches!(
            emit(&program(), &options),
            Err(EmitError::InvalidPackageName(_))
        ));

        let mut invalid = program();
        invalid.expressions[1].expression = Expression::Const {
            value: Value::Float(f64::NAN),
        };
        assert!(matches!(
            emit(
                &invalid,
                &Options {
                    package_name: "sample-map".to_string(),
                    runtime_dependency: RuntimeDependency::Version("0.1.0".to_string()),
                }
            ),
            Err(EmitError::NonFiniteFloat { node: 2 })
        ));
    }

    #[test]
    fn rejects_missing_expression_dependencies() {
        let mut invalid = program();
        let Some(node) = invalid.expressions.iter_mut().find(|node| node.id == 7) else {
            panic!("test program must contain call node 7");
        };
        node.expression = Expression::Call {
            function: ScalarFunction::Add,
            args: vec![5, 404],
        };

        assert!(matches!(
            emit(
                &invalid,
                &Options {
                    package_name: "sample-map".to_string(),
                    runtime_dependency: RuntimeDependency::Version("0.1.0".to_string()),
                }
            ),
            Err(EmitError::InvalidProgram(
                ProgramValidationError::MissingDependency {
                    node: 7,
                    dependency: 404,
                }
            ))
        ));
    }

    #[test]
    fn rejects_self_and_multi_node_expression_cycles() {
        let options = Options {
            package_name: "sample-map".to_string(),
            runtime_dependency: RuntimeDependency::Version("0.1.0".to_string()),
        };
        let mut self_cycle = program();
        let Some(node) = self_cycle.expressions.iter_mut().find(|node| node.id == 7) else {
            panic!("test program must contain call node 7");
        };
        node.expression = Expression::Call {
            function: ScalarFunction::Add,
            args: vec![7],
        };
        assert!(matches!(
            emit(&self_cycle, &options),
            Err(EmitError::InvalidProgram(
                ProgramValidationError::ExpressionCycle { cycle }
            )) if cycle == vec![7, 7]
        ));

        let mut multi_cycle = program();
        let Some(node) = multi_cycle.expressions.iter_mut().find(|node| node.id == 7) else {
            panic!("test program must contain call node 7");
        };
        node.expression = Expression::Call {
            function: ScalarFunction::Add,
            args: vec![9],
        };
        let Some(node) = multi_cycle.expressions.iter_mut().find(|node| node.id == 9) else {
            panic!("test program must contain call node 9");
        };
        node.expression = Expression::Call {
            function: ScalarFunction::Divide,
            args: vec![7, 8],
        };
        assert!(matches!(
            emit(&multi_cycle, &options),
            Err(EmitError::InvalidProgram(
                ProgramValidationError::ExpressionCycle { cycle }
            )) if cycle == vec![7, 9, 7]
        ));
    }

    #[test]
    fn rejects_static_target_name_collisions_before_emission() {
        let options = Options {
            package_name: "sample-map".to_string(),
            runtime_dependency: RuntimeDependency::Version("0.1.0".to_string()),
        };
        let mut binding_child = program();
        binding_child.root.bindings.push(Binding {
            target_field: "Nested".to_string(),
            expression: 1,
            target_type: ScalarType::String,
            repeating: false,
        });
        assert!(matches!(
            emit(&binding_child, &options),
            Err(EmitError::InvalidProgram(
                ProgramValidationError::BindingChildCollision {
                    target_path,
                    target_field,
                    binding: 5,
                    child: 0,
                }
            )) if target_path.is_empty() && target_field == "Nested"
        ));

        let mut duplicate_child = program();
        let repeated_child = duplicate_child.root.children[0].clone();
        duplicate_child.root.children.push(repeated_child);
        assert!(matches!(
            emit(&duplicate_child, &options),
            Err(EmitError::InvalidProgram(
                ProgramValidationError::DuplicateChildTarget {
                    target_path,
                    target_field,
                    first_child: 0,
                    duplicate_child: 2,
                }
            )) if target_path.is_empty() && target_field == "Nested"
        ));
    }

    #[test]
    fn generated_project_builds_and_matches_the_static_mapping() {
        let runtime = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .map(|parent| parent.join("codegen-runtime"))
            .unwrap();
        let output = TempDir::new("rust_codegen");
        let artifacts = emit(
            &program(),
            &Options {
                package_name: "sample-map".to_string(),
                runtime_dependency: RuntimeDependency::Path(runtime.display().to_string()),
            },
        )
        .unwrap();
        write_artifacts(output.path(), &artifacts);
        fs::write(
            output.path().join("src/main.rs"),
            r#"use codegen_runtime::{
    FunctionError, Instance, RuntimeError, SourcePathError, Value, field, group, repeated, scalar,
};

fn main() {
    let happy_source = source(Value::Int(8), Value::Int(2), Value::Bool(true));
    let actual = sample_map::execute(&happy_source).unwrap();
    let expected = group([
        field("Copied", scalar(Value::String("Ada".to_string()))),
        field("Numbers", repeated([scalar(Value::Int(7))])),
        field("Sum", scalar(Value::Int(10))),
        field("Selected", scalar(Value::Int(10))),
        field("Nested", repeated([group([field(
            "Constant",
            scalar(Value::String("fixed".to_string())),
        )])])),
        field("Rows", repeated([
            mapped_row(1, "a"),
            mapped_row(1, "b"),
            mapped_row(2, "c"),
        ])),
    ]);
    assert_eq!(actual, expected);

    let arithmetic = sample_map::execute(&source(
        Value::Int(8),
        Value::Int(2),
        Value::Bool(false),
    ));
    assert_eq!(
        arithmetic,
        Err(RuntimeError::Function(FunctionError::DivideByZero))
    );

    let not_bool = sample_map::execute(&source(
        Value::Int(8),
        Value::Int(2),
        Value::String("no".to_string()),
    ));
    assert_eq!(
        not_bool,
        Err(RuntimeError::NotABool {
            node: 10,
            found: "string",
        })
    );

    let missing = group([
        field("Name", scalar(Value::String("Ada".to_string()))),
        field("Condition", scalar(Value::Bool(true))),
    ]);
    assert!(matches!(
        sample_map::execute(&missing),
        Err(RuntimeError::SourcePath(SourcePathError::MissingField { field, .. }))
            if field == "First"
    ));
}

fn source(first: Value, second: Value, condition: Value) -> Instance {
    group([
        field("Name", scalar(Value::String("Ada".to_string()))),
        field("First", scalar(first)),
        field("Second", scalar(second)),
        field("Condition", scalar(condition)),
        field("Parents", repeated([
            parent(1, &["a", "b"]),
            parent(2, &["c"]),
        ])),
    ])
}

fn parent(id: i64, children: &[&str]) -> Instance {
    group([
        field("Id", scalar(Value::Int(id))),
        field(
            "Children",
            repeated(children.iter().map(|name| {
                group([field("Name", scalar(Value::String((*name).to_string())))])
            })),
        ),
    ])
}

fn mapped_row(parent_id: i64, child_name: &str) -> Instance {
    group([
        field("ParentId", scalar(Value::Int(parent_id))),
        field(
            "ChildName",
            scalar(Value::String(child_name.to_string())),
        ),
    ])
}
"#,
        )
        .unwrap();

        let result = Command::new("cargo")
            .args(["run", "--quiet"])
            .current_dir(output.path())
            .env("CARGO_TARGET_DIR", output.path().join("target"))
            .output()
            .unwrap();
        assert!(
            result.status.success(),
            "generated Rust project failed:\n{}\n{}",
            String::from_utf8_lossy(&result.stdout),
            String::from_utf8_lossy(&result.stderr)
        );
    }

    fn write_artifacts(directory: &Path, artifacts: &ArtifactSet) {
        for file in artifacts.files() {
            let path = directory.join(file.path.as_str());
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(path, &file.contents).unwrap();
        }
    }

    struct TempDir(PathBuf);

    impl TempDir {
        fn new(tag: &str) -> Self {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|duration| duration.as_nanos())
                .unwrap_or_default();
            let path = std::env::temp_dir().join(format!(
                "ferrule_{tag}_{}_{}",
                std::process::id(),
                nonce
            ));
            fs::create_dir_all(&path).unwrap();
            Self(path)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }
}
