using Ferrule.Runtime;

namespace Ferrule.Runtime.SmokeTests;

internal static partial class Program
{
    private sealed record Json5BoundaryCase(string Id, string Profile, string Input, string? Output, string? Typed, FerruleJson5Stage? Stage, FerruleJson5SyntaxKind? Kind, string? InputKind = null, long? Utf8Offset = null);
    // Literal projection of the independently authored 75-case contract.
    private static readonly Json5BoundaryCase[] Json5BoundaryCases =
    [
        new("strict-integer", "I", "{\"n\":7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("comments-trailing-comma", "I", "/*before*/{n:7,}// eof", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("unicode-text-single-quotes", "S", "{n:'Ada \u96ea'}", "{\n  \"n\": \"Ada \u96ea\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"Ada \u96ea\"}}}]}", null, null),
        new("hexadecimal", "I", "{n:0x10}", "{\n  \"n\": 16\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"16\"}}}]}", null, null),
        new("hexadecimal-negative", "I", "{n:-0X10}", "{\n  \"n\": -16\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"-16\"}}}]}", null, null),
        new("leading-plus", "I", "{n:+7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("leading-point", "F", "{n:.5}", "{\n  \"n\": 0.5\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Float\",\"bits_hex\":\"3fe0000000000000\"}}}]}", null, null),
        new("trailing-point", "F", "{n:5.}", "{\n  \"n\": 5.0\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Float\",\"bits_hex\":\"4014000000000000\"}}}]}", null, null),
        new("plus-leading-point", "F", "{n:+.5}", "{\n  \"n\": 0.5\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Float\",\"bits_hex\":\"3fe0000000000000\"}}}]}", null, null),
        new("exponent-retained", "F", "{n:1e0}", "{\n  \"n\": 1.0\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Float\",\"bits_hex\":\"3ff0000000000000\"}}}]}", null, null),
        new("integer-minus-zero-native-tag", "I", "{n:-0}", "{\n  \"n\": 0\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"0\"}}}]}", null, null),
        new("hex-minus-zero-native-tag", "I", "{n:-0x0}", "{\n  \"n\": 0\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"0\"}}}]}", null, null),
        new("float-minus-zero", "F", "{n:-0.0}", "{\n  \"n\": -0.0\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Float\",\"bits_hex\":\"8000000000000000\"}}}]}", null, null),
        new("bool", "B", "{n:true}", "{\n  \"n\": true\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Bool\",\"value\":true}}}]}", null, null),
        new("nullable-explicit-null", "N", "{n:null}", "{\n  \"n\": null\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"JsonNull\"}}}]}", null, null),
        new("i64-min-hex", "I", "{n:-0x8000000000000000}", "{\n  \"n\": -9223372036854775808\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"-9223372036854775808\"}}}]}", null, null),
        new("i64-max", "I", "{n:9223372036854775807}", "{\n  \"n\": 9223372036854775807\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"9223372036854775807\"}}}]}", null, null),
        new("integer-two53-plus1", "I", "{n:9007199254740993}", "{\n  \"n\": 9007199254740993\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"9007199254740993\"}}}]}", null, null),
        new("decimal-two53-plus1-rounds-once", "F", "{n:9007199254740993.0}", "{\n  \"n\": 9007199254740992.0\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Float\",\"bits_hex\":\"4340000000000000\"}}}]}", null, null),
        new("escaped-ascii-identifier", "I", "{\\u006e:7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("duplicate-last-wins", "I", "{n:1,n:7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("escaped-duplicate-name", "I", "{n:1,'\\u006e':7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("earlier-type-replaced", "I", "{n:'bad',n:7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("quoted-unicode-name", "U", "{'\u96ea':7}", "{\n  \"\u96ea\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"\u96ea\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("bom-and-json5-whitespace", "I", "\ufeff\u00a0{n:7}\u2028\u2029", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("line-comment-u2028", "I", "// before\u2028{n:7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("line-comment-u2029", "I", "// before\u2029{n:7}", "{\n  \"n\": 7\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}}]}", null, null),
        new("lf-string-continuation", "S", "{n:'a\\\nb'}", "{\n  \"n\": \"ab\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"ab\"}}}]}", null, null),
        new("crlf-string-continuation", "S", "{n:'a\\\r\nb'}", "{\n  \"n\": \"ab\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"ab\"}}}]}", null, null),
        new("separator-string-continuation", "S", "{n:'a\\\u2028b'}", "{\n  \"n\": \"ab\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"ab\"}}}]}", null, null),
        new("hex-string-escape", "S", "{n:'\\x41'}", "{\n  \"n\": \"A\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"A\"}}}]}", null, null),
        new("surrogate-pair-string", "S", "{n:'\\uD83D\\uDE00'}", "{\n  \"n\": \"\ud83d\ude00\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"\ud83d\ude00\"}}}]}", null, null),
        new("non-escape-character", "S", "{n:'\\z'}", "{\n  \"n\": \"z\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"z\"}}}]}", null, null),
        new("nul-escape", "S", "{n:'\\0'}", "{\n  \"n\": \"\\u0000\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"\\u0000\"}}}]}", null, null),
        new("vertical-tab-escape", "S", "{n:'\\v'}", "{\n  \"n\": \"\\u000b\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"\\u000b\"}}}]}", null, null),
        new("raw-tab-string", "S", "{n:'a\tb'}", "{\n  \"n\": \"a\\tb\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"a\\tb\"}}}]}", null, null),
        new("raw-u2028-string", "S", "{n:'a\u2028b'}", "{\n  \"n\": \"a\u2028b\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"a\u2028b\"}}}]}", null, null),
        new("markers-in-string-not-comments", "S", "{n:'/*not comment*/ [] {} //'}", "{\n  \"n\": \"/*not comment*/ [] {} //\"\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"String\",\"text\":\"/*not comment*/ [] {} //\"}}}]}", null, null),
        new("unquoted-unicode-boundary", "U", "{\u96ea:7}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnsupportedIdentifier, null, 1),
        new("escaped-unicode-identifier-boundary", "U", "{\\u96ea:7}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnsupportedIdentifier, null, 1),
        new("consecutive-comma", "I", "{n:7,,}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnexpectedToken),
        new("missing-colon", "I", "{n 7}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnexpectedToken),
        new("second-root-json-lines", "I", "{n:7}\n{n:8}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.TrailingRootValue),
        new("unterminated-block-comment", "I", "{n:7}/*", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnterminatedComment),
        new("unescaped-lf-string", "S", "{n:'a\nb'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.LineTerminatorInString),
        new("unpaired-surrogate-string", "S", "{n:'\\uD800'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidEscape),
        new("reversed-surrogate-string", "S", "{n:'\\uDC00\\uD800'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidEscape),
        new("legacy-octal-string-escape", "S", "{n:'\\1'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidEscape),
        new("nul-followed-digit", "S", "{n:'\\01'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidEscape),
        new("invalid-hex-string-escape", "S", "{n:'\\x0G'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidEscape),
        new("number-leading-zero", "I", "{n:01}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidNumber),
        new("number-separator", "I", "{n:1_0}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidNumber),
        new("empty-hexadecimal", "I", "{n:0x}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidNumber),
        new("empty-exponent", "F", "{n:1e+}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidNumber),
        new("unsigned64-plus1", "F", "{n:18446744073709551616}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.IntegerOutOfRange),
        new("signed64-minus1", "F", "{n:-9223372036854775809}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.IntegerOutOfRange),
        new("float-overflow", "N", "{n:1e400}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber),
        new("nonfinite-Infinity", "N", "{n:Infinity}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber, null, 3),
        new("nonfinite-minusInfinity", "N", "{n:-Infinity}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber, null, 3),
        new("nonfinite-plusInfinity", "N", "{n:+Infinity}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber, null, 3),
        new("nonfinite-NaN", "N", "{n:NaN}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber, null, 3),
        new("nonfinite-minusNaN", "N", "{n:-NaN}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber, null, 3),
        new("nonfinite-plusNaN", "N", "{n:+NaN}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber, null, 3),
        new("nonfinite-overwritten", "N", "{n:NaN,n:null}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.NonFiniteNumber),
        new("earlier-invalid-escape-overwritten", "S", "{n:'\\1',n:'valid'}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.InvalidEscape),
        new("nul-unquoted-value", "I", "{n:\u0000}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnexpectedToken),
        new("NEL-not-json5-whitespace", "I", "\u0085{n:7}", null, null, FerruleJson5Stage.Syntax, FerruleJson5SyntaxKind.UnexpectedToken),
        new("root-array-not-flat-rows", "I", "[{n:7}]", null, null, FerruleJson5Stage.Input, null, "RootObjectRequired"),
        new("nonnullable-null", "I", "{n:null}", null, null, FerruleJson5Stage.Input, null, "SchemaShape"),
        new("decimal-not-integer-tag", "I", "{n:1.0}", null, null, FerruleJson5Stage.Input, null, "SchemaShape"),
        new("u64-outside-signed-int", "I", "{n:9223372036854775808}", null, null, FerruleJson5Stage.Input, null, "SchemaShape"),
        new("integer-not-exact-float", "F", "{n:9007199254740993}", null, null, FerruleJson5Stage.Input, null, "SchemaShape"),
        new("undeclared-property", "I", "{n:7,x:8}", null, null, FerruleJson5Stage.Input, null, "UndeclaredProperty"),
        new("absent-remains-null", "I", "{}", "{}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Null\"}}}]}", null, null),
        new("duplicate-first-key-slot-schema-order", "K", "{m:3,n:1,n:7}", "{\n  \"n\": 7,\n  \"m\": 3\n}\n", "{\"kind\":\"Group\",\"fields\":[{\"name\":\"n\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"7\"}}},{\"name\":\"m\",\"instance\":{\"kind\":\"Scalar\",\"value\":{\"tag\":\"Int\",\"decimal\":\"3\"}}}]}", null, null),
    ];
}
